/* ─────────────────────────────────────────────────────────────────
 * 全球海事風險區 / Global Maritime Risk Zones
 * Demo 資料：邊界為近似值，僅供介面展示。實務上請以下列權威來源即時資料為準：
 *   - IMB / ReCAAP（海盜）          - JWC / Lloyd's JWLA-027（戰爭）
 *   - OFAC / EU / UN（制裁）        - 各國 NAVAREA / NOTMAR（軍演 / 臨航）
 *   - WMO / JMA / NOAA NHC（氣象） - MARPOL Annex VI / IMO MEPC（ECA）
 *   - NOAA Fisheries / IMO MEPC（保護 / 限速）
 *   - IMO Traffic Separation Schemes（壅塞）
 *
 * 每筆 zone 欄位：
 *   cat            類別 key（對應 RISK_ZONE_CATEGORIES）
 *   id             區域代碼
 *   level          風險分級：critical / high / medium / low / info
 *   name / name_en 中／英名稱
 *   type / type_en 區域類型（次分類）
 *   desc / desc_en 中／英說明
 *   source         資料來源 / 出處
 *   source_url     來源連結（可選）
 *   effective_from 生效時間（'年-月-日' 或描述性，例如 '全年' / 'seasonal Nov–Mar'）
 *   effective_to   結束時間（'進行中' / 'ongoing' / 或日期）
 *   coords         邊界座標 [[lat, lon], ...]（leaflet polygon 用）
 * ───────────────────────────────────────────────────────────────── */

window.RISK_ZONE_CATEGORIES = [
  /* 風險區 — 進入時觸發警示（red/orange 色系） */
  { key: "piracy",     label: "海盜 / 武裝搶劫高風險區", label_en: "Piracy / Armed Robbery",       color: "#ff4d4f", semantic: "risk" },
  { key: "war",        label: "戰爭 / 武裝衝突區",       label_en: "War / Armed Conflict",          color: "#a02030", semantic: "risk" },
  { key: "sanction",   label: "制裁 / 禁運 / 敏感港口", label_en: "Sanctions / Embargo",            color: "#ff8c00", semantic: "risk" },
  { key: "military",   label: "軍演 / 臨時禁航區",       label_en: "Military Exercise / NOTAM",      color: "#b069ff", semantic: "risk" },
  { key: "weather",    label: "氣象與海況高風險區",     label_en: "Weather / Heavy Seas",            color: "#1e90ff", semantic: "risk" },
  /* 操作參考 — 進入時觸發「請啟動通報程序」、「進入安全通道」提示（cyan/green 色系） */
  { key: "reporting",  label: "自願通報區 (VRA)",        label_en: "Voluntary Reporting Area",       color: "#00bfb3", semantic: "reporting" },
  { key: "corridor",   label: "安全通道 / 護航走廊",     label_en: "Safety Corridor / Transit Route",color: "#6ee094", semantic: "corridor" },
  /* 環保 / 保護 / 壅塞 — 屬於合規與航行注意（green/yellow 色系） */
  { key: "eca",        label: "環保排放管制區 (ECA)",   label_en: "Emission Control Area",           color: "#2ecc71", semantic: "compliance" },
  { key: "protected",  label: "保護區 / 鯨豚限速區",     label_en: "Protected / Whale Speed Limit",  color: "#1abc9c", semantic: "compliance" },
  { key: "congestion", label: "航道壅塞 / 避碰熱區",     label_en: "Congested Traffic Lane",          color: "#f5d04a", semantic: "advisory" },
];
/* 注意：港口錨地不算「風險區」而是「另一個風險監控維度」(window.ANCHORAGE_AREAS)
 * 對應 voyage-alert.html 的 anchorage 維度，獨立計算 + 獨立 threshold + 獨立圖層 */

/* ─────────────────────────────────────────────────────────────────
 * 風險區命中時的「建議動作清單」模板
 * 來源文件：
 *   - BMP5 (Best Management Practices to Deter Piracy v5, BIMCO/ICS/IGP&I/INTERTANKO/OCIMF, Jun 2018)
 *   - ITF List of Designated Risk Areas with Applicable Benefits, 13 March 2026
 *   - Liberia Marine Security Advisory 09/2023 Rev 7 — Anti-Piracy Checklist
 *   - GCPG (Global Counter Piracy Guidance)
 *
 * 每個 zone 透過 action_template 欄位指向其中一個 template key；命中時依此模板出建議動作。
 * 動作依「進入前 / 進入中 / 受攻擊 / 通報」階段分組，前端可摺疊顯示。
 * ───────────────────────────────────────────────────────────────── */
window.ZONE_ACTION_TEMPLATES = {
  // ─── ITF Warlike Operations Area（最高層級：ISPS 3 + 拒航權 + 5 天最低戰險加成）
  itf_woa: {
    designation:    "ITF Warlike Operations Area (WOA)",
    designation_cn: "ITF 戰爭風險區",
    isps_level:     3,
    bmp_level:      "BMP5 + GCPG（強制等同 ISPS Level 3）",
    refs: [
      "BMP5 §4 Planning / §5 Ship Protection Measures / §6 Reporting / §7 Ships under attack",
      "ITF Designation 1/2/4/5/6/8（依區域）— 2026-03-13",
      "Liberia Marine Security Advisory 09/2023 Rev 7 — Anti-Piracy Checklist",
      "GCPG Part 6 Crew Briefing / Part 7 Ship Hardening",
    ],
    phases: [
      { phase: "進入 VRA 之前 / Before entering VRA", items: [
        "向 MSCIO 提交 Vessel Movement Registration Form（前身為 MSCHOA；postmaster@mscio.eu）",
        "向 UKMTO 提交 Vessel Position Reporting Form — Initial Report（BMP5 Annex D）",
        "完成航線專屬風險評估（含替代路線、是否使用 PCASP 武裝安全人員）",
        "與保險公司確認 JWC / Lloyd's JWLA 加費條款；通知船員權益（5 天最低戰險加成 + 雙倍死亡傷害補償）",
        "向公司 DPA / CSO 通報並取得最終出航許可",
      ]},
      { phase: "進入 HRA 之前 / Before entering HRA", items: [
        "船舶 ISPS Security Level 設為 **Level 3**（強制），啟用最高等級安全措施",
        "向船員宣告權益：依 ITF 規定有權拒絕航行；如拒航，公司負擔遣返費用 + 2 個月基本工資補償",
        "依 BMP5 §4 進行全船船員簡報並完成演練（含警報、Citadel 撤離、通訊）",
        "測試所有警報、SSAS、內部通訊、PA 廣播；驗證 UKMTO / MSCIO 緊急聯絡電話在駕駛室與 Citadel",
        "Citadel 已備妥糧食、飲水、衛生用品、衛星電話 + VHF；演練全員撤離至 Citadel 並確認門禁",
        "確認推進機可全速運轉；確認 AIS 維持開啟（軍方追蹤用）但限制資訊欄位",
      ]},
      { phase: "進入 HRA 之後 / During transit", items: [
        "依 §6 提交 Position Report；持續監看 NAVAREA 警報與 UKMTO 更新",
        "管制駕駛室與機艙出入口為單一進入點；非值班船員撤離至 Safe Muster Point",
        "部署反登船障礙：高張力刺鐵絲（730/980mm 線圈直徑）、消防水帶噴射模式、泡沫水砲、探照燈",
        "移除可協助攀爬的繩索、梯子；風暴梯（Pilot Ladder）收回",
        "強化瞭望：增加額外瞭望員、縮短輪值、夜視鏡 / 熱顯像、雷達連續監視",
        "避免漂航、慢速、錨泊；尤其在 MSTC 走廊內全速通過",
        "VHF 減量使用，改用 Email 或衛星電話；只回應已知合法呼叫",
      ]},
      { phase: "若遭遇攻擊 / Under attack", items: [
        "BMP5 §7：啟動警報、廣播 PA、船員撤至 Citadel；持續鳴汽笛干擾攻擊者",
        "立即發送 SSAS（Ship Security Alert System）",
        "通知 UKMTO（+44 1923 958 545 / watchkeepers@ukmto.org）+ MSCIO + 船公司 CSO",
        "增速並進行迴避操作（操船產生水壓船尾效應，比單純加速更有效）",
        "部署所有水砲 / 探照燈；舷外射燈以強光阻撓攻擊者",
        "全員進入 Citadel 後門禁鎖死，與外界保持雙向通訊；軍方介入需「全員確認在 Citadel + 雙向通訊」兩條件",
      ]},
      { phase: "事件後通報 / After incident", items: [
        "對 UKMTO + MSCIO + 船旗國 + 公司 DPA 提交事件報告（BMP5 §7 表單）",
        "對 IMB Piracy Reporting Centre 提交副本",
        "保留 CCTV 錄影、現場照片（船舶受損、攻擊船特徵）",
        "驗證船員人數、傷亡、損害；依 ITF 規定，攻擊當日有額外補償資格",
      ]},
    ],
    benefits: [
      "依 ITF 2026-03-13 規定：最低 5 天戰險加成等於基本工資；其後依實際停留天數加給",
      "雙倍死亡與傷殘補償（compensation doubled for death and disability）",
      "船員享有拒航權；如拒航，公司負擔遣返費 + 兩個月基本工資補償",
      "船東須執行等同 ISPS Level 3 的強化安全措施",
    ],
  },

  // ─── ITF Extended Risk Zone（中層級：BMP 等級提升 + 攻擊當日加成）
  itf_erz: {
    designation:    "ITF Extended Risk Zone (ERZ)",
    designation_cn: "ITF 擴展風險區",
    isps_level:     2,
    bmp_level:      "BMP5 / BMP West Africa（提升至最新版）",
    refs: [
      "BMP5 §4 / §5 / §6",
      "BMP West Africa（如 Gulf of Guinea）",
      "ITF Designation 3 / 9 / 10 — 2026-03-13",
    ],
    phases: [
      { phase: "進入前 / Before entry", items: [
        "依最新 BMP（BMP5 或 BMP West Africa）執行風險評估與航線規劃",
        "通知 MDAT-GoG（西非）或 UKMTO（其它區域）並登記 Vessel Position Report",
        "船員簡報：說明 ITF 攻擊當日加成（100% 基本工資）與雙倍傷亡補償權益",
        "ISPS Security Level 提升至 Level 2",
      ]},
      { phase: "進入後 / During transit", items: [
        "依 BMP 部署反登船障礙；維持強化瞭望",
        "管制入口；Citadel 演練；通訊測試",
        "AIS 維持開啟（除非當地軍方建議關閉）；持續監看區域警報",
      ]},
      { phase: "若遭遇攻擊 / Under attack", items: [
        "啟動警報、SSAS、進入 Citadel；同 WOA 程序",
        "事件報告須提交至國際認可機構（MDAT-GoG 等）以證明 ITF 加成資格",
        "船日誌正式記載攻擊事件",
      ]},
    ],
    benefits: [
      "攻擊當日（且僅當日）享有 100% 基本工資加成",
      "攻擊當日傷亡享雙倍補償",
      "提升 BMP 等級為強制執行條件",
    ],
  },

  // ─── ITF High Risk Area（中高層級：ISPS 3 + 全期加成 + 拒航權）
  itf_hra: {
    designation:    "ITF High Risk Area (HRA)",
    designation_cn: "ITF 高風險區",
    isps_level:     3,
    bmp_level:      "BMP5 + GCPG",
    refs: [
      "BMP5 §4 / §5 / §6 / §7",
      "ITF Designation 7（黑海 HRA）— 2026-03-13",
    ],
    phases: [
      { phase: "進入前 / Before entry", items: [
        "向 UKMTO 提交 Vessel Position Report — Initial Report",
        "ISPS Security Level 設為 Level 3",
        "依 BMP5 完成船員簡報、Citadel 演練、通訊測試",
        "通知船員權益：實際停留期間皆享 100% 基本工資加成；雙倍傷亡補償；可拒航",
      ]},
      { phase: "進入後 / During transit", items: [
        "依 BMP5 §5 部署所有 SPM（Ship Protection Measures）",
        "持續監看 UKMTO / 區域軍方警報",
        "管制出入口、強化瞭望、避免慢速漂航",
      ]},
      { phase: "若遭遇攻擊 / Under attack", items: [
        "依 BMP5 §7 流程；同 WOA 程序",
      ]},
    ],
    benefits: [
      "依 ITF：實際停留 / 通過天數皆享 100% 基本工資加成",
      "雙倍死亡傷殘補償；可拒航 + 2 個月基本工資補償",
      "船東須執行等同 ISPS Level 3 強化安全措施",
    ],
  },

  // ─── 海盜 BMP West Africa（西非適用，補充 ERZ 不足之處）
  piracy_bmp_wa: {
    designation:    "BMP West Africa (Gulf of Guinea)",
    designation_cn: "BMP 西非版（幾內亞灣）",
    isps_level:     2,
    bmp_level:      "BMP West Africa（補 BMP5）",
    refs: [
      "BMP West Africa 4th edition",
      "ITF Designation 3 — Gulf of Guinea ERZ",
      "MDAT-GoG（Maritime Domain Awareness for the Gulf of Guinea）",
    ],
    phases: [
      { phase: "進入前 / Before entry", items: [
        "向 MDAT-GoG 提交 Reporting Form（西非地區的對應 UKMTO 機制）",
        "依 BMP West Africa 進行風險評估，考慮使用區域 Convoy（如有提供）",
        "ISPS Level 提升 Level 2",
        "與保險公司確認 JWC 加費（西非長期戰險區）",
      ]},
      { phase: "進入後 / During transit", items: [
        "部署反登船障礙：刺鐵絲、水砲、探照燈、CCTV",
        "管制出入口；夜間限縮對外通訊",
        "監看 MDAT-GoG 公告、區域海軍動態（奈及利亞、加納）",
      ]},
      { phase: "若遭遇攻擊 / Under attack", items: [
        "通知 MDAT-GoG（+33 2 98 22 88 88）+ 船旗國 + 公司 CSO",
        "啟動 SSAS + 警報 + Citadel 撤離",
        "事件後提交報告予 IMB Piracy Reporting Centre + MDAT-GoG（ITF 攻擊當日加成資格憑證）",
      ]},
    ],
    benefits: [
      "ITF ERZ：攻擊當日 100% 基本工資加成 + 雙倍傷亡補償",
      "BMP 等級提升為強制執行條件",
    ],
  },

  // ─── 自願通報區（reporting）— 進入時觸發「請啟動通報程序」流程
  reporting_general: {
    designation:    "Voluntary Reporting Area (VRA)",
    designation_cn: "自願通報區",
    isps_level:     null,
    bmp_level:      "BMP5 / GCPG（依區域）",
    refs: [
      "BMP5 §6 Reporting / GCPG Section 6",
      "Admiralty Charts Q6099 (WIO) / Q6112+Q6113 (SE Asia) / Q6114 (GoG)",
      "MC(18)48 - Global Counter Piracy Guidance",
    ],
    phases: [
      { phase: "進入 VRA 之前 / Before entering VRA", items: [
        "依該 VRA 所屬機構（MSCIO / MDAT-GoG / IFC Singapore / ReCAAP）取得最新指南與聯絡資訊",
        "船員簡報通報程序：誰、何時、何種頻率送 Initial / Daily / Final Report",
        "確認 SSAS、衛星電話、Email 通訊管道可用",
      ]},
      { phase: "進入 VRA / On entering", items: [
        "提交 **Initial Report**（依該機構表單）— 通常含：船名、IMO、MMSI、Call Sign、入區時間/座標、預計航程、貨物、船員國籍、武裝安全人員（若有）",
        "向 UKMTO（WIO）/ MDAT-GoG（GoG）/ IFC Singapore（SEA）登記船舶移動",
      ]},
      { phase: "在 VRA 期間 / During transit", items: [
        "依規定頻率提交 **Daily Position Report**（通常每 6 或 12 小時一次）",
        "監看區域警報與其他船舶 incident 報告",
        "如遇可疑接近或攻擊，即刻向該 VRA 機構通報 + 對國旗國 / 公司 CSO 同步",
      ]},
      { phase: "離開 VRA / On exit", items: [
        "提交 **Final Report**：離區時間/座標、靠港資訊、有無 incident",
      ]},
    ],
    benefits: [
      "獲得區域軍方 / 護衛艦的即時援助管道",
      "區域安全情資（IRTA / IRTB）共享",
      "船員權益依該 VRA 內的特定子區 ITF 規定（如 ITF WOA / HRA / ERZ）另行適用",
    ],
  },

  // ─── 安全通道（corridor）— 護航走廊 / TSS
  corridor_general: {
    designation:    "Safety Corridor / Transit Scheme",
    designation_cn: "安全通道 / 護航走廊",
    isps_level:     null,
    bmp_level:      "BMP5 §1（MSTC）/ COLREG Rule 10（TSS）",
    refs: [
      "BMP5 §1 Maritime Security Transit Corridor",
      "IMO COLREG Rule 10 Traffic Separation Schemes",
      "Admiralty Chart Q6099（IRTC / BAM TSS）",
      "MSCIO Group Transit Scheme",
    ],
    phases: [
      { phase: "進入通道前 / Before entering corridor", items: [
        "確認船速能保持通道內最低航速（IRTC 內建議全速通過）",
        "向 MSCIO 登記參加 Group Transit（如有提供）",
        "規劃精準的進入點 / 退出點時間，避免在 corridor 外慢速漂航",
      ]},
      { phase: "在通道內 / Inside corridor", items: [
        "全速通過、不漂航、不錨泊（規格 BMP5 §4）",
        "依 COLREG Rule 10 行駛分隔通道（東行 / 西行）",
        "AIS 維持開啟，便於軍方追蹤護航",
        "VHF 維持與護航艦聯絡頻道（IRTC 通常為 VHF 16 + 軍方指定頻道）",
      ]},
      { phase: "出通道 / Exiting corridor", items: [
        "提交 Final Position Report，確認離開時間與下一個 leg 計畫",
      ]},
    ],
    benefits: [
      "獲得軍方護航艦與空中監視涵蓋",
      "享受 Group Transit 編隊優勢（多艘船同時通過降低個別風險）",
      "事故發生時援助到達時間最短",
    ],
  },

  // ─── 制裁區（通用：與 BMP / ITF 無關，著重法律與合規）
  sanction_general: {
    designation:    "Sanctions / Embargo Zone",
    designation_cn: "制裁 / 禁運區",
    isps_level:     null,
    bmp_level:      null,
    refs: [
      "OFAC SDN List / EU Council Reg 833 / UN Security Council Resolutions",
      "船公司法律顧問建議",
    ],
    phases: [
      { phase: "進入前 / Before entry", items: [
        "向法律顧問與 DPA 確認該港 / 該貨主 / 該收貨人是否在 SDN / EU Annex / UN 名單",
        "確認貨物未列入禁運品（武器、軍民兩用、能源產品等）",
        "確認支付通路（避免使用美元結算列名銀行）",
        "考慮取得 OFAC General License 或 EU Annex 例外（如適用）",
        "船東與承租人簽署 Letter of Indemnity（LOI）；確認保險覆蓋",
      ]},
      { phase: "進入後 / During port call", items: [
        "保留完整文件鏈：BOL、貨主、收貨人、船員國籍、付款流水",
        "AIS 維持開啟（**不可關閉 AIS**，避免被列入「影子船隊」嫌疑）",
        "船員離港制度依當地規定（部分制裁港需事先取得船員簽證）",
      ]},
      { phase: "離港後 / After departure", items: [
        "保留所有港口紀錄至少 5 年備查",
        "向公司合規部門提交完整航次報告",
      ]},
    ],
    benefits: [],
  },
};
/* helper：依 action_template key 取出 template；找不到回 null */
window.getZoneActionTemplate = function(key) {
  return key ? (window.ZONE_ACTION_TEMPLATES[key] || null) : null;
};

window.RISK_ZONES = [
  /* ── 1. 海盜 / 武裝搶劫高風險區 ──────────────────────────────── */
  { cat: "piracy", id: "PIR-GoG-2026", level: "low",
    name: "幾內亞灣（西非）", name_en: "Gulf of Guinea",
    type: "海盜熱區（已大幅冷卻）", type_en: "Piracy hotspot (sharp decline)",
    desc: "IMB Q1 2026 全西非僅 1 起；自 2022 峰值大幅下降。BMP West Africa 仍建議；偶有近岸搶劫。ITF 仍維持為 Extended Risk Zone（攻擊當日適用戰險加成）。",
    desc_en: "IMB Q1 2026: just 1 incident in entire West Africa region — sharp decline since 2022 peak. BMP West Africa still recommended; occasional inshore robbery. ITF maintains Extended Risk Zone designation (war-risk benefit applies on day of attack only).",
    source: "ITF ERZ Designation 3 (Gulf of Guinea, since 2023-01-01) / IMB Piracy Reporting Centre Q1 2026 / MDAT-GoG",
    source_url: "https://www.icc-ccs.org/piracy-reporting-centre",
    effective_from: "ITF ERZ 自 2023-01-01；長期", effective_to: "進行中 / ongoing",
    action_template: "piracy_bmp_wa",
    itf_designation: "Extended Risk Zone (ERZ)",
    coords: [[6.8, -5.0], [6.8, 9.0], [-2.0, 9.0], [-2.0, 2.0], [3.0, -5.0]],
    source_kinds: ["doc", "official", "web"] },

  { cat: "piracy", id: "PIR-SOM-2026", level: "high",
    name: "索馬利亞外海 / 亞丁灣 (HRA 重啟)", name_en: "Off Somalia / Gulf of Aden (HRA reactivated)",
    type: "BMP5 高風險區 / 2026 重啟劫船", type_en: "BMP5 HRA / Hijacks resumed 2026",
    desc: "2026-04 一週內 Alkhary 2 (4/20)、Honour 25 (4/21)、Sward (4/26) 三船遭劫，自 2017 以來最嚴峻復發；Alkhary 2 已於 4/22 釋放，Honour 25 / Sward 仍被扣。母船 (dhow) 作業範圍延伸至離岸 600 nm。分析師推測紅海反海盜兵力分散創造機會（與 Houthi 之關聯未獲權威證實）。對應 ITF Designation 2（南紅海 / 亞丁灣 WOA）。",
    desc_en: "Three hijackings in one week April 2026 — Alkhary 2 (4/20), Honour 25 (4/21), Sward (4/26) — most severe resurgence since 2017. Mothership (dhow) operations extend to 600 nm offshore. Maps onto ITF Designation 2 (Southern Red Sea / Gulf of Aden WOA).",
    source: "ITF WOA Designation 2 (Southern Red Sea & Gulf of Aden, since 2024-03-19) / Al Jazeera / DefenceWeb / EU NAVFOR ATALANTA / UKMTO",
    source_url: "https://www.aljazeera.com/news/2026/5/1/why-is-piracy-rising-off-somalia-again-and-is-the-iran-war",
    effective_from: "ITF WOA 自 2024-03-19；劫船重啟 2026-04", effective_to: "進行中 / ongoing",
    action_template: "itf_woa",
    itf_designation: "Warlike Operations Area (WOA)",
    coords: [[16, 42], [16, 60], [4, 65], [-5, 55], [0, 45], [10, 42]],
    source_kinds: ["doc", "official", "web"] },

  { cat: "piracy", id: "PIR-SOMBASIN-2026", level: "high",
    name: "索馬利亞海盆（擴展區）", name_en: "Somali Basin (extended threat area)",
    type: "母船延伸打擊區", type_en: "Mothership-extended attack range",
    desc: "海盜以 dhow 為母船延伸至離岸 600 nm；商船於 IOR 西部需保持警戒、走 IRTC 護航走廊。屬 BMP5 高風險區。",
    desc_en: "Mothership-supported operations reach 600 nm offshore using dhows; merchant vessels in W Indian Ocean advised to use IRTC convoy corridor. Within BMP5 HRA scope.",
    source: "BMP5 (Indian Ocean HRA) / Windward / UKMTO / EU NAVFOR ATALANTA",
    source_url: "https://www.ukmto.org",
    effective_from: "2026-04", effective_to: "進行中 / ongoing",
    action_template: "itf_woa",
    itf_designation: "BMP5 HRA scope",
    coords: [[8, 50], [8, 68], [-8, 68], [-8, 50]],
    source_kinds: ["doc", "official", "web"] },

  { cat: "piracy", id: "PIR-SS-2026", level: "medium",
    name: "新加坡海峽 / 麻六甲", name_en: "Singapore Strait / Malacca",
    type: "錨地竊取 / 夜間登船", type_en: "Anchorage theft / Night boarding",
    desc: "2025 全年亞洲 132 起、SOMS 達 108 起（自 2007 來最高）；2025-07 印尼警逮捕主嫌團（Riau 11 人）後攻擊驟減；ReCAAP Q1 2026 亞洲僅 16 起（較 2025 Q1 的 44 起減少 64%）。",
    desc_en: "ReCAAP 2025: 132 incidents Asia-wide, 108 in SOMS (highest since 2007); sharp decline after Indonesian arrests of 11 in Riau Islands Jul 2025; ReCAAP Q1 2026: only 16 incidents Asia-wide (down 64% vs 44 in Q1 2025).",
    source: "ReCAAP ISC Annual Report 2025 / Jan 2026 brief",
    source_url: "https://www.recaap.org",
    effective_from: "全年", effective_to: "進行中 / ongoing",
    action_template: "piracy_bmp_wa",
    coords: [[3.5, 100], [3.5, 105.5], [0.5, 105.5], [-0.5, 102], [1, 99]],
    source_kinds: ["official"] },

  { cat: "piracy", id: "PIR-SULU-2026", level: "low",
    name: "蘇祿—西里伯斯海", name_en: "Sulu–Celebes Sea",
    type: "綁架勒贖區（已大幅冷卻）", type_en: "KFR zone (sharp decline)",
    desc: "ReCAAP 已於 2025-01 將威脅等級由 high 下調至 LOW；自 2020-01 起連續 6 年無 KFR 事件。Abu Sayyaf 殘餘仍存於 Sulu / Tawi-Tawi 區，緩速漁船與拖船仍應警戒。",
    desc_en: "ReCAAP downgraded threat from high to LOW in Jan 2025; no KFR incidents since Jan 2020 (6 consecutive years). Abu Sayyaf remnants persist in Sulu / Tawi-Tawi; slow fishing/tug vessels still advised to remain vigilant.",
    source: "ReCAAP Guidance 2025 / PCG advisories",
    source_url: "https://www.recaap.org/resources/ck/files/guide/Recaap_guidance_FA(single).pdf",
    effective_from: "2025-01（下調 LOW）", effective_to: "進行中 / ongoing",
    action_template: "piracy_bmp_wa",
    coords: [[8, 118], [8, 124], [3, 124.5], [3, 118]],
    source_kinds: ["official"] },

  /* ── 2. 戰爭 / 武裝衝突區 ─────────────────────────────────────── */
  { cat: "war", id: "WAR-BLK-2026", level: "critical",
    name: "黑海（俄烏戰區）", name_en: "Black Sea (RU-UA war zone)",
    type: "JWLA 戰區 / USV 攻擊俄油輪", type_en: "JWLA war risk / USV strikes on RU tankers",
    desc: "Risk Intelligence 預測 2026 全球國家武力攻擊船舶首位；烏方公開以無人水面艇打擊俄油輪；UA 港口 7 日戰險升至約 0.5% 船價，俄 BS 港 0.65–0.8%。ITF Designation 7 將整個黑海列為 HRA（自 2023-11-01）、北黑海另列為 WOA（Designation 5）。",
    desc_en: "Risk Intelligence ranks Black Sea #1 for state-on-shipping attacks in 2026; UA released USV strike footage on RU tankers; UA-port 7-day war risk ~0.5% of hull, RU BS ports 0.65–0.8%. ITF designates entire Black Sea as HRA (Designation 7, since 2023-11-01), with Northern Black Sea as WOA (Designation 5).",
    source: "ITF WOA Designation 5 + HRA Designation 7 (2026-03-13 revision) / JWC / Lloyd's JWLA-027 / Risk Intelligence 2026 forecast",
    source_url: "https://www.lmalloyds.com",
    effective_from: "ITF WOA/HRA 自 2023-11-01；戰爭自 2022-02-24", effective_to: "進行中 / ongoing",
    action_template: "itf_hra",
    itf_designation: "Warlike Operations Area (north) + High Risk Area",
    coords: [[47.2, 28], [47.2, 41.5], [42, 41.5], [42, 28]],
    source_kinds: ["doc", "official", "web"] },

  { cat: "war", id: "WAR-UKR-PORT-2026", level: "critical",
    name: "烏克蘭港口（Odesa / Yuzhny）", name_en: "Ukrainian Ports (Odesa / Yuzhny)",
    type: "俄軍持續打擊港口設施", type_en: "Continued RU strikes on port terminals",
    desc: "Odesa / Pivdennyi (Yuzhne) / Chornomorsk 多次遭俄飛彈與無人機攻擊；2025-11 Izmail 港 gas tanker 受損、2025-12 多艘土耳其籍船在 Odesa 受損、2024-10 Pivdennyi 散貨船 Paresa 受損；船員傷亡與保費維持高位。對應 ITF Designation 6（全烏克蘭港口 WOA）。",
    desc_en: "Odesa / Pivdennyi (Yuzhne) / Chornomorsk repeatedly hit by RU missiles & drones; gas tanker damaged at Izmail Nov 2025, Turkish-owned vessels damaged at Odesa Dec 2025, bulker Paresa damaged at Pivdennyi Oct 2024. Maps to ITF Designation 6 (all Ukrainian ports WOA).",
    source: "ITF WOA Designation 6 (All Ukrainian ports, since 2022-03-01) / Maritime Executive / NorthStandard / Ukrainian MIU",
    source_url: "https://maritime-executive.com",
    effective_from: "ITF WOA 自 2022-03-01", effective_to: "進行中 / ongoing",
    action_template: "itf_woa",
    itf_designation: "Warlike Operations Area (WOA)",
    coords: [[46.8, 30.5], [46.8, 32.0], [45.8, 32.0], [45.8, 30.5]],
    source_kinds: ["doc", "web"] },

  { cat: "war", id: "WAR-RED-2026", level: "high",
    name: "紅海 / Bab-el-Mandeb（Houthi）", name_en: "Red Sea / Bab-el-Mandeb (Houthi)",
    type: "Houthi 重新威脅；攻擊未實際重啟", type_en: "Houthi resumed threats; no confirmed attacks yet",
    desc: "2025-11 至 2026-02 暫無確認攻擊；2026-02-28 美以對伊朗動武後 Houthi 公開表態恢復攻擊；多數承運仍走好望角。對應 ITF Designation 1（葉門海岸 12nm WOA，自 2018-03-01）+ Designation 2（南紅海/亞丁灣 WOA，自 2024-03-19）。**NAVCENT 子區**：12°N–16°N、46°E 以西 + Bab al Mandab Strait 為攻擊熱點極高威脅子區（依 Liberia Marine Security Advisory 09/2023 Rev 7）；攻擊範圍曾達離岸 100 nm。**OPG (Operation Prosperity Guardian)** 由 CMF / CTF-153 在 Southern Red Sea 進行存在嚇阻任務。",
    desc_en: "Houthis publicly threatened to resume targeting shipping after US-Israel strikes on Iran (Feb 28 2026). Most carriers still routing via Cape of Good Hope. Maps to ITF Designation 1 (12nm off Yemeni coast WOA, since 2018-03-01) + Designation 2 (Southern Red Sea/Gulf of Aden WOA, since 2024-03-19). **NAVCENT sub-zone**: 12°N–16°N, west of 46°E + Bab al Mandab Strait identified as highest-threat attack hotspot (per Liberia Marine Security Advisory 09/2023 Rev 7); attacks reached up to 100 nm offshore. **OPG (Operation Prosperity Guardian)** runs presence-and-deterrence missions in Southern Red Sea under CMF / CTF-153.",
    source: "ITF WOA Designations 1 & 2 / Liberia MSA 09/2023 Rev 7 / NAVCENT / UKMTO / MARAD 2026-006 / CMF / OPG (CTF-153)",
    source_url: "https://www.ukmto.org",
    effective_from: "ITF WOA 自 2018-03-01 / 2024-03-19；Houthi 威脅自 2023-11", effective_to: "進行中 / ongoing",
    action_template: "itf_woa",
    itf_designation: "Warlike Operations Area (WOA) ×2 + NAVCENT 極高威脅子區",
    coords: [[20, 36], [20, 46], [11, 46], [11, 41]],
    source_kinds: ["doc", "official", "web"] },

  { cat: "war", id: "WAR-RED-NAVCENT-2026", level: "critical",
    name: "南紅海 NAVCENT 極高威脅子區", name_en: "Southern Red Sea NAVCENT Highest-Threat Sub-zone",
    type: "Houthi 飛彈/無人機/水雷攻擊熱點", type_en: "Houthi missile / UAV / mine attack hotspot",
    desc: "NAVCENT 於 Liberia Marine Security Advisory 09/2023 Rev 7 標示「南紅海 12°N–16°N、46°E 以西 + Bab al Mandab Strait」為「持續高度威脅」攻擊熱點。Houthi 已多次以反艦飛彈、反艦彈道飛彈、無人機、WBIED 攻擊商船；近葉門海岸佈雷有時脫纜漂入主航道。**Liberian flag 強制 ISPS Level 3**，COMUSNAVCENT 建議 AIS 關閉時須每 2–3 小時提交位置報告。",
    desc_en: "NAVCENT identifies sub-zone 12°N–16°N west of 46°E + Bab al Mandab Strait as 'continued high threat' attack hotspot (per Liberia MSA 09/2023 Rev 7). Houthis have attacked merchant ships with anti-ship missiles, anti-ship ballistic missiles, UAVs, and WBIEDs; mines near Yemen coast occasionally drift into traffic lanes. **Liberian-flag vessels mandated ISPS Level 3**; if AIS is off, ships must position-report to COMUSNAVCENT every 2–3 hrs.",
    source: "NAVCENT / Liberia Marine Security Advisory 09/2023 Rev 7 (12 Mar 2025) / OPG (CTF-153)",
    source_url: "https://www.cusnc.navy.mil",
    effective_from: "2023-11（依 MSA 09/2023）", effective_to: "進行中 / ongoing",
    action_template: "itf_woa",
    itf_designation: "NAVCENT Highest-Threat Sub-zone（在 ITF WOA 內）",
    coords: [[16, 41], [16, 46], [12, 46], [12, 43.2]],
    source_kinds: ["doc"] },

  { cat: "war", id: "WAR-HORM-2026", level: "critical",
    name: "波斯灣 / 荷莫茲海峽（2026 伊朗戰）", name_en: "Persian Gulf / Strait of Hormuz (2026 Iran War)",
    type: "海峽封閉 / 佈雷 / 美軍反封鎖", type_en: "Strait closure / Mining / US counter-blockade",
    desc: "2026-02-28 美以動武、暗殺 Khamenei；伊朗封閉海峽、佈雷扣船；2026-04-13 至 05-29 美軍封鎖伊朗港口；商船通量降至戰前 5%（4 月僅 191 艘）。對應 ITF Designation 8（波斯灣/荷莫茲海峽/阿曼灣 WOA，自 2026-03-06 生效，反映 Iran 戰升級）。",
    desc_en: "Iran closed Strait & laid mines after US-Israel strikes (Feb 28 2026); only 191 vessels crossed in April (≈5% of pre-war level). ITF Designation 8 (Persian Gulf/Hormuz/Gulf of Oman WOA) took effect 2026-03-06 in response to Iran war escalation.",
    source: "ITF WOA Designation 8 (since 2026-03-06) / Wikipedia 2026 Iran war / Strait of Hormuz crisis / US naval blockade of Iran",
    source_url: "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_crisis",
    effective_from: "ITF WOA 自 2026-03-06；戰爭升級 2026-02-28", effective_to: "2026-05-29 停火（談判延長中）",
    action_template: "itf_woa",
    itf_designation: "Warlike Operations Area (WOA)",
    coords: [[30, 48], [30, 58], [24, 58], [24, 48]],
    source_kinds: ["doc", "web"] },

  { cat: "war", id: "WAR-AZOV-2026", level: "critical",
    name: "亞速海 / 刻赤海峽（北 45°03'N）", name_en: "Sea of Azov / Strait of Kerch (north of 45°03'N)",
    type: "ITF WOA 戰爭風險區", type_en: "ITF Warlike Operations Area",
    desc: "亞速海與刻赤海峽北緯 45°03'N 以北全部水域與港口；俄烏戰爭期間長期衝突區，自 2023-11-01 列為 ITF Designation 4 WOA。涵蓋克里米亞東岸 + 俄南方港口（Taganrog、Rostov、Mariupol、Berdyansk）。",
    desc_en: "All waters and ports of Sea of Azov and Strait of Kerch north of 45°03'00\"N. Long-standing conflict zone during RU-UA war; ITF Designation 4 WOA since 2023-11-01. Covers eastern Crimea + Russian southern ports (Taganrog, Rostov, Mariupol, Berdyansk).",
    source: "ITF WOA Designation 4 (Sea of Azov / Strait of Kerch, since 2023-11-01) / JWC / Lloyd's JWLA-027",
    source_url: "https://www.itfseafarers.org",
    effective_from: "ITF WOA 自 2023-11-01", effective_to: "進行中 / ongoing",
    action_template: "itf_woa",
    itf_designation: "Warlike Operations Area (WOA)",
    coords: [[47.3, 34.7], [47.3, 39.5], [45.05, 39.5], [45.05, 34.7]],
    source_kinds: ["doc", "official"] },

  { cat: "war", id: "WAR-GOO-2026", level: "high",
    name: "阿曼灣 ERZ（北 24°N）", name_en: "Gulf of Oman ERZ (north of 24°N)",
    type: "ITF 擴展風險區（伊朗戰外延）", type_en: "ITF Extended Risk Zone (Iran war spillover)",
    desc: "ITF Designation 9：阿曼灣 24°00'N 緯線以南 + Ra's al Hadd 燈塔 035° 方位線以西的水域，自 2026-03-06 列為 ERZ，與 ITF #8 波斯灣 WOA 互補。攻擊當日適用 100% 基本工資加成與雙倍傷亡補償。",
    desc_en: "ITF Designation 9: waters south of 24°00'N latitude and west of the 035° bearing line from Ra's al Hadd light. Designated ERZ since 2026-03-06, complementing ITF #8 Persian Gulf WOA. 100% basic-wage bonus + doubled compensation apply on attack day.",
    source: "ITF ERZ Designation 9 (Gulf of Oman, since 2026-03-06)",
    source_url: "https://www.itfseafarers.org",
    effective_from: "ITF ERZ 自 2026-03-06", effective_to: "進行中 / ongoing",
    action_template: "itf_erz",
    itf_designation: "Extended Risk Zone (ERZ)",
    coords: [[24, 57.1], [24, 60.97], [22.5, 59.8], [22.5, 57.1]],
    source_kinds: ["doc"] },

  { cat: "war", id: "WAR-EMED-2026", level: "high",
    name: "東地中海（黎凡特）", name_en: "Eastern Mediterranean (Levant)",
    type: "區域衝突 / 海上軍事活動", type_en: "Regional conflict / Naval activity",
    desc: "以哈與黎巴嫩外海軍事活動延續；伊朗戰升級後黎凡特水域風險再上升；JWLA 戰險加費維持。ITF Designation 10 將以色列沿岸 12 海浬列為 ERZ（自 2026-03-13）。",
    desc_en: "Israel-Hamas + Lebanon offshore military activity continues; Levant risk rose further after Iran war escalation; JWLA war-risk surcharge maintained. ITF Designation 10 lists 12NM off Israel coastline as ERZ (since 2026-03-13).",
    source: "ITF ERZ Designation 10 (12NM off Israel, since 2026-03-13) / JWC / Lloyd's JWLA",
    source_url: "https://www.lmalloyds.com",
    effective_from: "ITF ERZ 自 2026-03-13；衝突自 2023-10", effective_to: "進行中 / ongoing",
    action_template: "itf_erz",
    itf_designation: "Extended Risk Zone (ERZ)",
    coords: [[35.5, 32], [35.5, 36.5], [31, 36.5], [31, 32]],
    source_kinds: ["doc", "official"] },

  /* ── 3. 制裁 / 禁運 / 敏感港口區 ──────────────────────────────── */
  { cat: "sanction", id: "SAN-RU-BAL-2026", level: "high",
    name: "俄羅斯波羅的海港口", name_en: "Russian Baltic Ports",
    type: "G7 油價上限 + EU 20th package", type_en: "G7 price cap + EU 20th package",
    desc: "Primorsk / Ust-Luga / St Petersburg；EU 20th package (2026-04-23 採納) 已制裁 632 艘船；2026-02-28 比利時於 EEZ 扣押影子船隊 Ethera 號（Operation Blue Intruder、法海軍協力）。",
    desc_en: "Primorsk / Ust-Luga / St Petersburg; EU 20th package (adopted Apr 23 2026) brings sanctioned vessels to 632; Belgium seized shadow-fleet Ethera in its EEZ Feb 28 2026 (Operation Blue Intruder with French navy support).",
    source: "EU Council 20th sanctions package / OFAC",
    source_url: "https://www.consilium.europa.eu",
    effective_from: "2022-12-05", effective_to: "進行中 / ongoing",
    coords: [[60.5, 27], [60.5, 35], [58, 35], [58, 27]],
    action_template: "sanction_general",
    source_kinds: ["official"] },

  { cat: "sanction", id: "SAN-RU-BLK-2026", level: "high",
    name: "俄羅斯黑海港口", name_en: "Russian Black Sea Ports",
    type: "G7 油價上限 + EU 影子船隊制裁", type_en: "G7 price cap + EU shadow-fleet sanctions",
    desc: "Novorossiysk / Tuapse — EU 20th 將 Tuapse 列入 Annex XLVII 制裁港；7 日戰險升至 0.65–0.8% 船價。",
    desc_en: "Novorossiysk / Tuapse — EU 20th package adds Tuapse to Annex XLVII sanctioned ports; 7-day war risk 0.65–0.8% of hull.",
    source: "EU Council Reg 833 (20th amendment) / OFAC",
    source_url: "https://www.consilium.europa.eu",
    effective_from: "2026-04-23 採納 / 04-24 生效（Tuapse 新增）", effective_to: "進行中 / ongoing",
    coords: [[45.5, 36.5], [45.5, 39.5], [43.5, 39.5], [43.5, 36.5]],
    action_template: "sanction_general",
    source_kinds: ["official"] },

  { cat: "sanction", id: "SAN-RU-MUR-2026", level: "high",
    name: "俄羅斯北極港 Murmansk", name_en: "Russian Arctic Port Murmansk",
    type: "EU 20th 新列制裁港", type_en: "EU 20th newly sanctioned port",
    desc: "EU 20th package 將 Murmansk 列入 Annex XLVII 制裁港（與 Tuapse 同批）；理由為協助規避油價上限。",
    desc_en: "Added to EU Annex XLVII sanctioned ports (with Tuapse) under 20th package — used to circumvent oil price cap.",
    source: "EU Council Reg 833 (20th amendment)",
    source_url: "https://www.consilium.europa.eu",
    effective_from: "2026-04-24", effective_to: "進行中 / ongoing",
    coords: [[69.4, 32.5], [69.4, 34.0], [68.7, 34.0], [68.7, 32.5]],
    action_template: "sanction_general",
    source_kinds: ["official"] },

  { cat: "sanction", id: "SAN-IR-2026", level: "critical",
    name: "伊朗港口（戰時封鎖）", name_en: "Iranian Ports (wartime blockade)",
    type: "OFAC 二級制裁 + 美軍封鎖", type_en: "OFAC secondary sanctions + US blockade",
    desc: "Bandar Abbas / Kharg Island — OFAC 二級制裁長期維持；2026-04-13 至 05-29 美軍封鎖（停火延長談判中、SDN 制裁仍進行）；任何泊靠列入 SDN 風險。",
    desc_en: "Bandar Abbas / Kharg Island — OFAC secondary sanctions remain in force; US naval blockade Apr 13 – May 29 2026 (ceasefire under negotiation, SDN sanctions ongoing); SDN listing risk on any call.",
    source: "OFAC / Wikipedia 2026 US naval blockade of Iran",
    source_url: "https://ofac.treasury.gov",
    effective_from: "2018-11-05（戰時 2026-04-13）", effective_to: "進行中 / ongoing",
    coords: [[28, 50], [28, 58], [25, 58], [25, 50]],
    action_template: "sanction_general",
    source_kinds: ["official", "web"] },

  { cat: "sanction", id: "SAN-DPRK-2026", level: "critical",
    name: "北韓港口", name_en: "DPRK Ports",
    type: "UN 全面禁運 + STS 監控", type_en: "UN total embargo + STS monitoring",
    desc: "Nampo / Wonsan / Rajin — UN 禁運；多國（NZ/CA/AU/FR/JP）2025–26 持續監視 STS；OFAC 維持 SDN 名單擴充。",
    desc_en: "Nampo / Wonsan / Rajin — UN embargo; NZ/CA/AU/FR/JP continue STS surveillance 2025–26; OFAC expands SDN listings.",
    source: "UNSC Res 1718/2270/2371/2397 / OFAC DPRK advisory",
    source_url: "https://www.un.org/securitycouncil",
    effective_from: "2006-10-14", effective_to: "進行中 / ongoing",
    coords: [[43, 124], [43, 131], [37.5, 131], [37.5, 124]],
    action_template: "sanction_general",
    source_kinds: ["official"] },

  { cat: "sanction", id: "SAN-VEN-2026", level: "low",
    name: "委內瑞拉港口（GL 鬆綁）", name_en: "Venezuelan Ports (GL eased)",
    type: "OFAC GL 47/50A 鬆綁", type_en: "OFAC GLs 47 / 50A easing",
    desc: "2026-01-03 Maduro 移除後，OFAC 於 2/3 發 GL 47、2/13 發 GL 50、2/18 升級為 GL 50A，授權 BP/Chevron/Eni/Repsol/Shell/Maurel & Prom 等於 Jose / La Cruz 從事石油作業；其他主體仍需嚴格盡職調查。",
    desc_en: "After Maduro's removal on Jan 3 2026, OFAC issued GL 47 (Feb 3), GL 50 (Feb 13), and GL 50A (Feb 18) authorizing BP/Chevron/Eni/Repsol/Shell/Maurel & Prom oil-sector operations at Jose / La Cruz; other parties still require strict due diligence.",
    source: "OFAC Venezuela GL 47, 48, 49, 50, 50A / Crowell / Morgan Lewis",
    source_url: "https://ofac.treasury.gov/sanctions-programs-and-country-information/venezuela-related-sanctions",
    effective_from: "2026-02-03（GL 47 起鬆綁）", effective_to: "依 GL 動態調整",
    coords: [[12, -72], [12, -61], [10, -61], [10, -72]],
    action_template: "sanction_general",
    source_kinds: ["official", "web"] },

  { cat: "sanction", id: "SAN-SY-2026", level: "high",
    name: "敘利亞港口", name_en: "Syrian Ports",
    type: "EU + OFAC 禁運", type_en: "EU and OFAC embargo",
    desc: "Latakia / Tartus — 禁運維持；俄海軍 Tartus 基地進出列敏感；2024 政權轉換後仍未全面解除。",
    desc_en: "Latakia / Tartus — embargo remains; Russian Tartus naval base sensitive; not fully lifted despite 2024 regime change.",
    source: "OFAC Syria Sanctions / EU Council Reg 36/2012",
    source_url: "https://ofac.treasury.gov",
    effective_from: "2011-05", effective_to: "進行中 / ongoing",
    coords: [[36, 35], [36, 37], [34, 37], [34, 35]],
    action_template: "sanction_general",
    source_kinds: ["official"] },

  { cat: "sanction", id: "SAN-CU-2026", level: "medium",
    name: "古巴港口", name_en: "Cuban Ports",
    type: "Helms-Burton + US 禁運", type_en: "Helms-Burton + US Embargo",
    desc: "Helms-Burton Act Titles III/IV；對 US persons 與美元交易維持限制。",
    desc_en: "Helms-Burton Act Titles III/IV; restricted for US persons and USD transactions.",
    source: "OFAC Cuban Assets Control Regulations",
    source_url: "https://ofac.treasury.gov",
    effective_from: "1962（強化 2017）", effective_to: "進行中 / ongoing",
    coords: [[24, -85], [24, -75], [19, -75], [19, -85]],
    action_template: "sanction_general",
    source_kinds: ["official"] },

  /* ── 4. 軍演 / 臨時禁航區 ─────────────────────────────────────── */
  { cat: "military", id: "MIL-TWS-2026", level: "high",
    name: "台灣海峽", name_en: "Taiwan Strait",
    type: "PLA 演習 NOTMAR 高頻區", type_en: "Frequent PLA exercise NOTMAR",
    desc: "2025-12-29「Justice Mission 2025」130 架次飛機、90 過中線 + 海上實彈；2026-04 Liaoning 南下、CCG 於 12 nm 接戰 VHF 頻道盤查商船。",
    desc_en: "PLA 'Justice Mission 2025' (Dec 29 2025): 130 sorties, 90 crossed centerline, live-fire at sea; April 2026 Liaoning moved south, CCG hailing merchant ships on VHF within 12 nm contiguous zone.",
    source: "China MSA NAVAREA XI / Global Taiwan Institute / The Diplomat",
    source_url: "https://www.msa.gov.cn",
    effective_from: "依公告 / per NOTMAR", effective_to: "依公告 / per NOTMAR",
    coords: [[26, 118], [26, 122], [22, 122], [22, 118]],
    source_kinds: ["official"] },

  { cat: "military", id: "MIL-SCS-2026", level: "medium",
    name: "南海", name_en: "South China Sea",
    type: "多方主權爭議 + 演習", type_en: "Multi-claimant dispute + exercises",
    desc: "Balikatan 2026（2026-04-20 至 05-08）為史上最大：17,000 人，日本首派 1,400 人含 Hyuga 級 JS Ise、Type 88 反艦首部署 Luzon 北外海；PLA 南部戰區於 Luzon 以東反制演習。",
    desc_en: "Balikatan 2026 (Apr 20 – May 8) largest ever: 17,000 troops, Japan first deployed 1,400 personnel incl JS Ise (DDH-182) + Type 88 anti-ship N of Luzon; PLA Southern Theatre counter-drills E of Luzon.",
    source: "USNI News / SCMP / Naval News",
    source_url: "https://news.usni.org",
    effective_from: "2026-04-20", effective_to: "2026-05-08（年度）",
    coords: [[20, 110], [20, 120], [7, 120], [7, 110]],
    source_kinds: ["official"] },

  { cat: "military", id: "MIL-ECS-2026", level: "medium",
    name: "東海 / 釣魚台周邊", name_en: "East China Sea / Senkaku",
    type: "爭議水域 + 海警執法", type_en: "Disputed waters + CCG/JCG presence",
    desc: "中日台爭議水域；CCG 與 JCG 持續對峙；2013 後 ADIZ 重疊；2025-26 CCG 進入連續日數創新高。",
    desc_en: "Disputed waters; persistent CCG / JCG standoff; overlapping ADIZ since 2013; CCG intrusion days hit record in 2025-26.",
    source: "JCG NAVAREA XI / CN MSA",
    source_url: "https://www6.kaiho.mlit.go.jp",
    effective_from: "長期", effective_to: "進行中 / ongoing",
    coords: [[27, 122], [27, 127], [24, 127], [24, 122]],
    source_kinds: ["official"] },

  { cat: "military", id: "MIL-KOR-2026", level: "medium",
    name: "朝鮮半島周邊", name_en: "Korean Peninsula",
    type: "演習 + DPRK 飛彈試射", type_en: "Exercises + DPRK missile tests",
    desc: "2026 起 DPRK 至少 7 次彈道試射（1/3/4 月含 hypersonic、MRBM、cluster-warhead，4 月密集 4 次）落東海；US-ROK Freedom Shield 3 月演習；NOTMAR 頻發。",
    desc_en: "At least 7 DPRK ballistic launches in 2026 (Jan/Mar/Apr incl hypersonic, MRBM, cluster-warhead, with 4 in April alone) into East Sea; US-ROK Freedom Shield drills in March; frequent NOTMARs.",
    source: "USNI News / ROK NAVAREA XIII / KCG",
    source_url: "https://news.usni.org",
    effective_from: "依公告 / per NOTMAR", effective_to: "依公告 / per NOTMAR",
    coords: [[40, 123], [40, 131], [35, 131], [35, 123]],
    source_kinds: ["official", "web"] },

  { cat: "military", id: "MIL-HAW-2026", level: "low",
    name: "夏威夷周邊 RIMPAC 2026", name_en: "Off Hawaii RIMPAC 2026",
    type: "30th RIMPAC（雙年度）", type_en: "30th RIMPAC (biennial)",
    desc: "2026-06-24 至 07-31：31 國、40 艘船、5 艘潛艇、140 架機、25,000+ 人；夏威夷主島周邊海空多區實彈與 SINKEX。",
    desc_en: "Jun 24 – Jul 31 2026: 31 nations, 40 ships, 5 subs, 140 aircraft, 25,000+ personnel; multiple live-fire & SINKEX zones around Hawaiian Islands.",
    source: "US Pacific Fleet / US 3rd Fleet NAVAREA XII",
    source_url: "https://www.cpf.navy.mil/rimpac/",
    effective_from: "2026-06-24", effective_to: "2026-07-31",
    coords: [[24, -163], [24, -154], [18, -154], [18, -163]],
    source_kinds: ["official"] },

  /* ── 5. 氣象與海況高風險區 ────────────────────────────────────── */
  { cat: "weather", id: "WX-CGH-2026", level: "high",
    name: "好望角 / Agulhas 異常浪", name_en: "Cape of Good Hope / Agulhas Rogue Waves",
    type: "強流逆風異常浪區", type_en: "Current-against-swell rogue-wave zone",
    desc: "Agulhas 洋流逆 SW 湧浪生成 20 m+ 異常波；Houthi 緩解後仍多承運走好望角，使此區流量倍增。",
    desc_en: "Agulhas current against SW swell — 20 m+ rogue waves; despite Houthi pause many carriers still routing via Cape — traffic doubled vs pre-2024.",
    source: "SAWS / NOAA OPC",
    source_url: "https://www.weathersa.co.za",
    effective_from: "5–9 月加劇", effective_to: "全年",
    coords: [[-32, 15], [-32, 24], [-38, 24], [-38, 15]],
    source_kinds: ["official", "web"] },

  { cat: "weather", id: "WX-NATL-HUR-2026", level: "medium",
    name: "北大西洋颶風帶 2026", name_en: "North Atlantic Hurricane Belt 2026",
    type: "NOAA 預測偏低於平均", type_en: "NOAA forecasts below-average season",
    desc: "NOAA 2026 預測：55% 低於常年、35% 接近常年、10% 高於常年；8–14 命名風暴、3–6 颶風、1–3 大型颶風；El Niño 發展抑制。",
    desc_en: "NOAA 2026 outlook: 55% below-normal, 35% near-normal, 10% above; 8–14 named storms, 3–6 hurricanes, 1–3 major; suppressed by developing El Niño.",
    source: "NOAA NHC 2026 Atlantic outlook (May 22 2026)",
    source_url: "https://www.nhc.noaa.gov",
    effective_from: "2026-06-01", effective_to: "2026-11-30",
    coords: [[32, -98], [32, -55], [10, -55], [10, -85]],
    source_kinds: ["official"] },

  { cat: "weather", id: "WX-WPAC-2026", level: "high",
    name: "西北太平洋颱風帶 2026", name_en: "Western North Pacific Typhoon Belt 2026",
    type: "颱風 / 熱帶氣旋活躍區", type_en: "Active tropical cyclone basin",
    desc: "2026 異常早起：Nokaen (1/15) 為自 2019 以來最早命名風暴；Sinlaku 4/10 達颱風、4/12 升 super typhoon；預估全年 22–30 名命名風暴。",
    desc_en: "Unusually early 2026 season: Nokaen (Jan 15) earliest-named since 2019; Sinlaku reached typhoon Apr 10, super typhoon Apr 12; pre-season range 22–30 named storms.",
    source: "JMA RSMC Tokyo / JTWC",
    source_url: "https://www.jma.go.jp/en/typh",
    effective_from: "全年（2026 異常自 1 月起）", effective_to: "11 月",
    coords: [[28, 125], [28, 155], [10, 155], [10, 125]],
    source_kinds: ["official"] },

  { cat: "weather", id: "WX-BOB-2026", level: "medium",
    name: "孟加拉灣熱帶氣旋區", name_en: "Bay of Bengal Cyclone Area",
    type: "雙峰季節熱帶氣旋", type_en: "Bimodal cyclone season",
    desc: "4–5 月與 10–11 月雙峰；常侵襲印度東岸與孟加拉沿岸；2026 El Niño 對後峰影響混合（總數可能減少、但強氣旋比例可能上升）。",
    desc_en: "Bimodal cyclone season Apr–May & Oct–Nov; frequent landfall on east India & Bangladesh; 2026 El Niño effects on late-season are mixed (total numbers may decrease but intense cyclone ratio may rise).",
    source: "IMD RSMC New Delhi",
    source_url: "https://mausam.imd.gov.in",
    effective_from: "4–5 月、10–11 月", effective_to: "—",
    coords: [[22, 80], [22, 95], [10, 95], [10, 80]],
    source_kinds: ["official", "web"] },

  { cat: "weather", id: "WX-DRAKE-2026", level: "critical",
    name: "Drake Passage / 合恩角", name_en: "Drake Passage / Cape Horn",
    type: "強西風帶 + 冰山", type_en: "Westerlies + icebergs",
    desc: "全年強西風帶 (40°–60°S, Roaring 40s/Furious 50s)；冰山風險；建議盡量繞道巴拿馬或蘇伊士。",
    desc_en: "Year-round Roaring 40s / Furious 50s; iceberg risk; Panama or Suez routing recommended where feasible.",
    source: "NOAA OPC / SHN Argentina",
    source_url: "https://ocean.weather.gov",
    effective_from: "全年", effective_to: "全年",
    coords: [[-52, -76], [-52, -54], [-62, -54], [-62, -76]],
    source_kinds: ["web"] },

  /* ── 6. 環保排放管制區 ECA ────────────────────────────────────── */
  { cat: "eca", id: "ECA-MED-2026", level: "info",
    name: "地中海 SECA", name_en: "Mediterranean SECA",
    type: "SECA（硫 ≤0.1%）", type_en: "SECA (sulphur ≤0.1%)",
    desc: "整個地中海納入 SECA 自 2025-05-01 生效；2026 年起多國強化港口檢測與處罰（船載燃油取樣、文件審查）；土耳其等已建立國內處罰框架。",
    desc_en: "Entire Mediterranean SECA in force since May 1 2025; in 2026 several states strengthened enforcement (onboard sampling, documentation, port inspections); Turkey among countries with national penalty frameworks.",
    source: "MARPOL Annex VI / IMO MEPC.361(79) / EMSA",
    source_url: "https://www.imo.org",
    effective_from: "2025-05-01", effective_to: "進行中 / ongoing",
    coords: [[46, -6], [46, 36], [30, 36], [30, -6]],
    source_kinds: ["official"] },

  { cat: "eca", id: "ECA-CAN-ARC-2026", level: "info",
    name: "加拿大北極 ECA（新）", name_en: "Canadian Arctic ECA (new)",
    type: "新增 ECA（2026-03-01 起）", type_en: "Newly entered into force Mar 1 2026",
    desc: "MEPC.392(82)；加拿大北極水域納入；硫 ≤0.1% 自 2027-03-01 起執行（含 Tier III NOx）；過渡期至 2027-02。",
    desc_en: "MEPC.392(82); Canadian Arctic waters included; sulphur ≤0.1% from Mar 1 2027 + Tier III NOx; transition period until Feb 2027.",
    source: "IMO MEPC.392(82) / DNV",
    source_url: "https://www.imo.org",
    effective_from: "2026-03-01（生效）/ 2027-03-01（執行）", effective_to: "進行中 / ongoing",
    coords: [[80, -120], [80, -60], [65, -60], [65, -120]],
    source_kinds: ["official", "web"] },

  { cat: "eca", id: "ECA-NOR-SEA-2026", level: "info",
    name: "挪威海 ECA（新）", name_en: "Norwegian Sea ECA (new)",
    type: "新增 ECA（2026-03-01 起）", type_en: "Newly entered into force Mar 1 2026",
    desc: "MEPC.392(82)；挪威 EEZ + 峽灣海域；硫 ≤0.1% 自 2027-03-01 起執行；範圍接俄羅斯邊境。",
    desc_en: "MEPC.392(82); Norwegian EEZ, fjords & coastal waters to Russian border; sulphur ≤0.1% from Mar 1 2027.",
    source: "IMO MEPC.392(82) / DNV",
    source_url: "https://www.imo.org",
    effective_from: "2026-03-01（生效）/ 2027-03-01（執行）", effective_to: "進行中 / ongoing",
    coords: [[78, -5], [78, 32], [62, 32], [62, -5]],
    source_kinds: ["official"] },

  { cat: "eca", id: "ECA-NA-E-2026", level: "info",
    name: "北美 ECA（東岸）", name_en: "North American ECA (East Coast)",
    type: "SECA + NECA", type_en: "SECA + NECA",
    desc: "200 nm 沿岸區；硫 ≤0.1%；Tier III NOx 適用 2016 後鋪龍骨新造船。",
    desc_en: "200-nm coastal zone; sulphur ≤0.1%; Tier III NOx for newbuilds keel-laid after Jan 1 2016.",
    source: "MARPOL Annex VI / IMO MEPC.176(58)",
    source_url: "https://www.imo.org",
    effective_from: "2012-08-01 / 2016-01-01", effective_to: "進行中 / ongoing",
    coords: [[60, -52], [60, -68], [25, -82], [25, -76]],
    source_kinds: ["official"] },

  { cat: "eca", id: "ECA-NA-W-2026", level: "info",
    name: "北美 ECA（西岸）", name_en: "North American ECA (West Coast)",
    type: "SECA + NECA", type_en: "SECA + NECA",
    desc: "200 nm 沿岸區；硫 ≤0.1%；Tier III NOx 適用新造船。",
    desc_en: "200-nm coastal zone; sulphur ≤0.1%; Tier III NOx for newbuilds.",
    source: "MARPOL Annex VI / IMO MEPC.176(58)",
    source_url: "https://www.imo.org",
    effective_from: "2012-08-01 / 2016-01-01", effective_to: "進行中 / ongoing",
    coords: [[60, -135], [60, -125], [33, -116], [33, -125]],
    source_kinds: ["official"] },

  { cat: "eca", id: "ECA-NS-BAL-2026", level: "info",
    name: "北海 + 波羅的海 ECA", name_en: "North Sea + Baltic Sea ECA",
    type: "SECA + NECA", type_en: "SECA + NECA",
    desc: "硫 ≤0.1%（2015-01-01 起）；NECA Tier III NOx 2021-01-01 起新造船。",
    desc_en: "Sulphur ≤0.1% (since 2015-01-01); NECA Tier III NOx for newbuilds since 2021-01-01.",
    source: "MARPOL Annex VI / IMO MEPC.286(71)",
    source_url: "https://www.imo.org",
    effective_from: "2007-11-19 / 2021-01-01", effective_to: "進行中 / ongoing",
    coords: [[66, -2], [66, 30], [51, 30], [51, -2]],
    source_kinds: ["official"] },

  { cat: "eca", id: "ECA-CN-DECA-2026", level: "info",
    name: "中國沿海 DECA", name_en: "China Domestic ECA",
    type: "DECA 全國沿海", type_en: "Nationwide coastal DECA",
    desc: "全國沿海 12 nm（含珠三角、長三角、環渤海與海南）2019-01 起硫 ≤0.5%；內河（長江、西江）與海南 2020/2022 起 ≤0.1%；2025-26 沿海持續推進 ≤0.1% 評估。",
    desc_en: "Nationwide coastal 12 nm (PRD/YRD/Bohai/Hainan) sulphur ≤0.5% since 2019-01; inland (Yangtze/Xijiang) & Hainan ≤0.1% since 2020/2022; 2025-26 evaluating coastal-wide ≤0.1%.",
    source: "China MOT / China MSA DECA plan",
    source_url: "https://www.msa.gov.cn",
    effective_from: "2019-01-01", effective_to: "進行中 / ongoing",
    coords: [[40, 117], [40, 124], [18, 113], [18, 108]],
    source_kinds: ["official"] },

  /* ── 7. 保護區 / 限速區 / 鯨豚保護區 ──────────────────────────── */
  { cat: "protected", id: "PRO-NARW-NE-2026", level: "info",
    name: "北大西洋露脊鯨 SMA（東北）", name_en: "NARW Seasonal Mgmt Area (NE US)",
    type: "強制限速區（10 kn）", type_en: "Mandatory speed limit (10 kn)",
    desc: "Cape Cod 灣季節性 SMA；≥65 ft 船舶限速 10 kn；違規最高 USD 35k 罰金。",
    desc_en: "Cape Cod Bay seasonal SMA; ≥65-ft vessels limited to 10 kn; fines up to USD 35k.",
    source: "NOAA Fisheries 50 CFR 224.105",
    source_url: "https://www.fisheries.noaa.gov",
    effective_from: "1 月 1 日", effective_to: "5 月 15 日",
    coords: [[43, -71], [43, -68], [40, -68], [40, -71]],
    source_kinds: ["official"] },

  { cat: "protected", id: "PRO-NARW-SE-2026", level: "info",
    name: "北大西洋露脊鯨 SMA（東南）", name_en: "NARW SMA (SE US)",
    type: "強制限速區（10 kn）", type_en: "Mandatory speed limit (10 kn)",
    desc: "Florida–Georgia 沿岸 NARW 育幼區；≥65 ft 船舶限速 10 kn。",
    desc_en: "Florida–Georgia coast (NARW calving ground); ≥65-ft vessels limited to 10 kn.",
    source: "NOAA Fisheries 50 CFR 224.105",
    source_url: "https://www.fisheries.noaa.gov",
    effective_from: "11 月 15 日", effective_to: "4 月 15 日",
    coords: [[33, -82], [33, -77], [27, -77], [27, -82]],
    source_kinds: ["official"] },

  { cat: "protected", id: "PRO-GBR-2026", level: "info",
    name: "大堡礁海洋公園 (PSSA)", name_en: "Great Barrier Reef Marine Park (PSSA)",
    type: "強制引航 + IMO PSSA", type_en: "Compulsory pilotage + IMO PSSA",
    desc: "強制引航、Two-way 路徑與排放限制；IMO PSSA。",
    desc_en: "Compulsory pilotage, two-way routes, discharge limits; IMO PSSA.",
    source: "AMSA / GBRMPA / IMO MEPC.133(53)",
    source_url: "https://www.amsa.gov.au",
    effective_from: "1990（強化 2005）", effective_to: "進行中 / ongoing",
    coords: [[-10, 143], [-10, 154], [-24, 154], [-24, 145]],
    source_kinds: ["official"] },

  { cat: "protected", id: "PRO-GAL-2026", level: "info",
    name: "加拉巴哥海洋保護區（擴展）", name_en: "Galápagos Marine Reserve (expanded)",
    type: "198,000 km² MPA + 30,000 km² no-take", type_en: "198,000 km² MPA + 30,000 km² no-take",
    desc: "2022 擴展至 198,000 km²；含 Galápagos–Cocos Swimway（30,000 km² no-take）；與 CR/PA/CO 形成 CMAR 跨國保護網（合計 500,000 km²）；嚴格限制漁撈與危險品航行。",
    desc_en: "Expanded to 198,000 km² in 2022; includes Galápagos–Cocos Swimway (30,000 km² no-take); part of CMAR (CR/PA/CO/EC) 500,000 km² network; strict fishing & hazmat restrictions.",
    source: "Galápagos Conservancy / WildAid",
    source_url: "https://www.galapagos.org",
    effective_from: "1998（擴展 2022-01）", effective_to: "進行中 / ongoing",
    coords: [[2, -93], [2, -87], [-3, -87], [-3, -93]],
    source_kinds: ["official"] },

  { cat: "protected", id: "PRO-PEL-2026", level: "info",
    name: "地中海 Pelagos Sanctuary", name_en: "Pelagos Sanctuary",
    type: "三國海洋哺乳動物保護區", type_en: "Trilateral marine mammal sanctuary",
    desc: "法義摩三國海洋哺乳動物保護區；避免高速、夜間航行與聲納試驗。",
    desc_en: "FR/IT/MC trilateral marine mammal sanctuary; avoid high speed, night transit and sonar trials.",
    source: "Pelagos Agreement (1999)",
    source_url: "https://www.sanctuaire-pelagos.org",
    effective_from: "2002-02-21", effective_to: "進行中 / ongoing",
    coords: [[44, 6], [44, 10], [41, 10], [41, 6]],
    source_kinds: ["official"] },

  /* ── 8. 航道壅塞 / 避碰高風險區 ──────────────────────────────── */
  { cat: "congestion", id: "CON-SUE-2026", level: "high",
    name: "蘇伊士運河進出區", name_en: "Suez Canal Approaches",
    type: "緩慢復甦 + 伊朗戰後再受挫", type_en: "Slow recovery + new Iran-war setback",
    desc: "通量仍低於 2023 同期約 60%；2025-12 CMA CGM 全船 ULCV 復航、2026-01 起亞美與亞地中海航線部分回流；但 2026-03-29 CMA CGM 因伊朗戰升級暫停 Suez、繞 Cape；Hapag-Lloyd 同步調整。",
    desc_en: "Throughput still ~60% below 2023; CMA CGM full ULCV resumption Dec 2025 + India-US service via Suez Jan 2026; but on Mar 29 2026 CMA CGM suspended Suez (Cape routing) after Iran war escalation; Hapag-Lloyd followed.",
    source: "Suez Canal Authority / Maritime News / Logfret",
    source_url: "https://www.suezcanal.gov.eg",
    effective_from: "2024-01（繞道起）", effective_to: "進行中 / ongoing",
    coords: [[32, 32], [32, 33.5], [29, 33.5], [29, 32]],
    source_kinds: ["official"] },

  { cat: "congestion", id: "CON-PAN-2026", level: "low",
    name: "巴拿馬運河進出區", name_en: "Panama Canal Approaches",
    type: "已完全恢復 + El Niño Watch", type_en: "Fully recovered + El Niño Watch",
    desc: "Gatun Lake 2026-02-07 達 88.9 ft 觸發溢洪；ACP 已恢復每日 38–40 班（達戰前水準）。NOAA 2026 春發布 El Niño Watch（May-Jul 2026 ENSO 中性 82–98%），2026/27 冬季可能形成；LNG 船仍偏好 Cape 繞航。",
    desc_en: "Gatun Lake reached 88.9 ft Feb 7 2026 (spillway opened); ACP fully restored to 38–40 slots/day (pre-drought level). NOAA Spring 2026 issued El Niño Watch (82–98% ENSO-neutral May-Jul 2026, possible El Niño 2026/27 winter); LNG carriers still prefer Cape route.",
    source: "Panama Canal Authority (ACP) / NOAA CPC",
    source_url: "https://www.pancanal.com",
    effective_from: "2023-08（限額）", effective_to: "進行中 / ongoing",
    coords: [[10, -80.5], [10, -78.5], [8.2, -78.5], [8.2, -80.5]],
    source_kinds: ["official"] },

  { cat: "congestion", id: "CON-DOV-2026", level: "high",
    name: "多佛海峽 / 英吉利海峽", name_en: "Dover Strait / English Channel",
    type: "TSS 分道通行最忙海域", type_en: "Busiest TSS in the world",
    desc: "全球最忙 TSS；雙向 ≥400 艘/日；強制 AIS + VHF Ch 11 報告（CNIS）。",
    desc_en: "Busiest TSS in the world; ≥400 transits/day bi-directional; mandatory AIS + VHF Ch 11 (CNIS).",
    source: "IMO COLREG Rule 10 / UK MCA CNIS",
    source_url: "https://www.gov.uk/government/organisations/maritime-and-coastguard-agency",
    effective_from: "1967（首條 TSS）", effective_to: "進行中 / ongoing",
    coords: [[51.5, 0.8], [51.5, 2.5], [50.5, 2.5], [50.5, 0.8]],
    source_kinds: ["official"] },

  { cat: "congestion", id: "CON-SS-2026", level: "high",
    name: "新加坡海峽 TSS", name_en: "Singapore Strait TSS",
    type: "東西向主幹 + 高會遇率", type_en: "Main E-W lane + high encounter rate",
    desc: "東西向幹線；錨地飽和、會遇率高；STRAITREP 強制報告升級；2026-01 起 SOMS 仍有零星 PIR。",
    desc_en: "Main E-W lane; saturated anchorages, high encounter rate; STRAITREP mandatory reporting; sporadic robbery incidents continue in Jan 2026.",
    source: "IMO STRAITREP / MPA Singapore",
    source_url: "https://www.mpa.gov.sg",
    effective_from: "1981（強化 1998）", effective_to: "進行中 / ongoing",
    coords: [[3, 100], [3, 105.5], [0.7, 105.5], [0.7, 100]],
    source_kinds: ["official"] },

  { cat: "congestion", id: "CON-CGH-RTE-2026", level: "medium",
    name: "好望角繞道航線", name_en: "Cape of Good Hope Detour Route",
    type: "繞道擁堵 + 港口排程壓力", type_en: "Detour congestion + port scheduling pressure",
    desc: "紅海緊張使大量集裝箱、散貨繞 Cape；2026 持續，南非港口（Durban、Cape Town）排隊與 Singapore/Colombo 補給壓力大；中段 St Helena 加油成新熱點。",
    desc_en: "Persistent Red Sea diversions add load on Cape route 2026; South African ports (Durban, Cape Town) face queues; Singapore/Colombo bunkering pressure; St Helena emerging as bunker hub.",
    source: "Bertling / Adriaports / Lloyd's List",
    source_url: "https://www.bertling.com/news-pool/blog/suez-canal/",
    effective_from: "2024-01", effective_to: "進行中 / ongoing",
    coords: [[-30, 14], [-30, 35], [-40, 35], [-40, 14]],
    source_kinds: ["official"] },

  { cat: "congestion", id: "CON-BOS-2026", level: "medium",
    name: "博斯普魯斯海峽", name_en: "Bosphorus Strait",
    type: "土耳其單向通行 + 強流", type_en: "Turkey one-way traffic + strong currents",
    desc: "土耳其單向通行；霧季與夜間特別管制；6–8 節向南表層流；俄烏戰使俄油輪流量集中。",
    desc_en: "Turkey one-way traffic; fog/night restrictions; 6–8 kn southbound surface current; RU tanker traffic concentrated since war.",
    source: "Turkish Straits VTS",
    source_url: "https://atlas.kiyiemniyeti.gov.tr",
    effective_from: "1994（VTS 1998）", effective_to: "進行中 / ongoing",
    coords: [[41.4, 28.5], [41.4, 29.5], [40.9, 29.5], [40.9, 28.5]],
    source_kinds: ["official"] },

  /* ── 9. 自願通報區 (VRA) ─────────────────────────────────────────
   *   進入時觸發「請啟動通報程序」提示，而非警示。BMP5 / MC(18)48 / GCPG 三大區。
   *   邊界為依文件與 Chart Q6099/Q6112/Q6113/Q6114 的近似多邊形。 */

  { cat: "reporting", id: "RPT-MSCIO-VRA-2026", level: "info",
    name: "MSCIO / UKMTO 自願通報區（西印度洋）", name_en: "MSCIO / UKMTO VRA (Western Indian Ocean)",
    type: "BMP5 西印度洋通報區", type_en: "BMP5 WIO Voluntary Reporting Area",
    desc: "BMP5 §1 定義的 UKMTO Voluntary Reporting Area，涵蓋紅海、亞丁灣、阿拉伯海、整個西印度洋至 78°E、北至 Suez 30°N、南至 10°S。Admiralty Chart Q6099 標示。MSCHOA 於 2025 改名為 MSCIO (Maritime Security Centre – Indian Ocean)。所有船進入此 VRA 應向 UKMTO 提交 Initial Report，並在 MSCIO 登記船舶移動。",
    desc_en: "UKMTO Voluntary Reporting Area defined by BMP5 §1, covering Red Sea, Gulf of Aden, Arabian Sea, entire WIO out to 78°E, north to Suez 30°N, south to 10°S. Shown on Admiralty Chart Q6099. MSCHOA was renamed MSCIO (Maritime Security Centre – Indian Ocean) in 2025. All vessels entering this VRA should submit Initial Report to UKMTO and register movements with MSCIO.",
    source: "BMP5 §1 / UKMTO / MSCIO (was MSCHOA) / Admiralty Chart Q6099",
    source_url: "https://www.ukmto.org",
    effective_from: "BMP5 v5（2018-06）", effective_to: "進行中 / ongoing",
    action_template: "reporting_general",
    coords: [[30, 32], [30, 78], [-10, 78], [-10, 40], [12, 43], [30, 32]],
    source_kinds: ["official", "web"] },

  { cat: "reporting", id: "RPT-MDAT-VRA-2026", level: "info",
    name: "MDAT-GoG 自願通報區（幾內亞灣）", name_en: "MDAT-GoG VRA (Gulf of Guinea)",
    type: "MC(18)48 西非通報區", type_en: "MC(18)48 West Africa Voluntary Reporting Area",
    desc: "MC(18)48 / MDAT-GoG 定義的西非自願通報區，由法國 (Brest) 與英國 (Portsmouth) 海軍共同營運。涵蓋象牙海岸/賴比瑞亞邊界至安哥拉/那米比亞邊界沿岸海域，可延伸至 00°N 005°E。Admiralty Chart Q6114 標示。進入時提交 Initial Report 給 watchkeepers@mdat-gog.org（+33 2 98 22 88 88）。",
    desc_en: "Voluntary Reporting Area for West Africa defined by MC(18)48 / MDAT-GoG, jointly operated by French (Brest) and UK (Portsmouth) navies. Covers Liberia/Ivory Coast border to Angola/Namibia border, extending to 00°N 005°E. Shown on Admiralty Chart Q6114. Submit Initial Report on entry: watchkeepers@mdat-gog.org (+33 2 98 22 88 88).",
    source: "MC(18)48 - Gulf of Guinea Region V3 / MDAT-GoG / Admiralty Chart Q6114 / SHOM 8801CS",
    source_url: "https://www.mdat-gog.org",
    effective_from: "2016-06（MC(18)48 V3 2018-06）", effective_to: "進行中 / ongoing",
    action_template: "reporting_general",
    coords: [[10, -10], [10, 10], [-18, 10], [-18, -5], [10, -10]],
    source_kinds: ["official"] },

  { cat: "reporting", id: "RPT-IFC-VRA-2026", level: "info",
    name: "IFC Singapore / ReCAAP 通報區（東南亞）", name_en: "IFC Singapore / ReCAAP VRA (Southeast Asia)",
    type: "GCPG 東南亞通報區", type_en: "GCPG Southeast Asia Voluntary Reporting Area",
    desc: "GCPG Annex C 定義的東南亞自願通報區，涵蓋麻六甲海峽、新加坡海峽、南海南部、蘇祿—西里伯斯海。Admiralty Charts Q6112 + Q6113 標示。IFC (Information Fusion Centre, Singapore) 為主要 24/7 監看中心；ReCAAP ISC 為政府間情資共享機制。可疑接近或事件向最近 Coastal State MRCC 通報。",
    desc_en: "Voluntary Reporting Area for Southeast Asia defined by GCPG Annex C, covering Malacca Strait, Singapore Strait, southern South China Sea, and Sulu-Celebes Seas. Shown on Admiralty Charts Q6112 + Q6113. IFC (Information Fusion Centre, Singapore) is the 24/7 monitoring hub; ReCAAP ISC handles inter-governmental information sharing.",
    source: "GCPG Annex C / IFC Singapore / ReCAAP ISC / Admiralty Charts Q6112 + Q6113",
    source_url: "https://www.infofusioncentre.gov.sg",
    effective_from: "2006-11（ReCAAP ISC）", effective_to: "進行中 / ongoing",
    action_template: "reporting_general",
    coords: [[20, 95], [20, 130], [-10, 130], [-10, 100], [8, 95]],
    source_kinds: ["official", "web"] },

  /* ── 10. 安全通道 / 護航走廊 ────────────────────────────────────
   *   進入時觸發「進入安全通道」提示。IRTC、BAM TSS 等。 */

  { cat: "corridor", id: "COR-IRTC-2026", level: "info",
    name: "IRTC 國際建議護航走廊（亞丁灣）", name_en: "IRTC Internationally Recommended Transit Corridor (Gulf of Aden)",
    type: "BMP5 / EUNAVFOR 護航走廊", type_en: "BMP5 / EUNAVFOR Transit Corridor",
    desc: "亞丁灣內的軍方建立護航走廊，分東行 / 西行兩條分隔航線。由 EU NAVFOR ATALANTA 與 CMF 共同護航，是 MSTC (Maritime Security Transit Corridor) 主要組成。商船應全速通過、不漂航、不錨泊。可向 MSCIO 登記參加 Group Transit 編隊。對應 Admiralty Chart Q6099。",
    desc_en: "Military-established transit corridor in Gulf of Aden with separated eastbound / westbound lanes. Jointly patrolled by EU NAVFOR ATALANTA and CMF; main component of MSTC (Maritime Security Transit Corridor). Vessels should transit at full speed without drifting/anchoring. Group Transit scheme available via MSCIO. Shown on Admiralty Chart Q6099.",
    source: "BMP5 §1 / EU NAVFOR ATALANTA / CMF / Admiralty Chart Q6099",
    source_url: "https://www.eunavfor.eu",
    effective_from: "2009-02（IRTC 建立）", effective_to: "進行中 / ongoing",
    action_template: "corridor_general",
    coords: [[14.5, 45], [14.5, 53], [11.8, 53], [11.8, 45]],
    source_kinds: ["official"] },

  { cat: "corridor", id: "COR-BAM-2026", level: "info",
    name: "BAM TSS 巴布艾爾曼德海峽分隔通道", name_en: "BAM TSS (Bab el Mandeb Traffic Separation Scheme)",
    type: "BMP5 / IMO TSS 海峽分隔通道", type_en: "BMP5 / IMO TSS Strait Separation",
    desc: "BMP5 §1 標示的 Bab el Mandeb 海峽分隔通道，連接紅海與亞丁灣的關鍵 chokepoint。屬於 MSTC 一環，並與 IRTC 透過雙向航道相連。海峽寬度最窄處僅約 26 km；商船須依 IMO COLREG Rule 10 駛入正確分隔通道。**NAVCENT 標示為極高威脅子區** — 受 Houthi 飛彈/無人機/WBIED 攻擊熱點。",
    desc_en: "Bab el Mandeb Strait Traffic Separation Scheme per BMP5 §1, connecting Red Sea and Gulf of Aden as a critical chokepoint. Part of MSTC, connected to IRTC via a two-way route. Narrowest at ~26 km; vessels must use correct lane per IMO COLREG Rule 10. **Identified by NAVCENT as highest-threat sub-zone** — hotspot for Houthi missile / UAV / WBIED attacks.",
    source: "BMP5 §1 / IMO COLREG Rule 10 / Admiralty Chart Q6099 / NAVCENT MSA 09/2023",
    source_url: "https://www.imo.org",
    effective_from: "IMO TSS 長期；BMP5 §1（2018-06）", effective_to: "進行中 / ongoing",
    action_template: "corridor_general",
    coords: [[12.8, 43.1], [12.8, 43.55], [12.4, 43.55], [12.4, 43.1]],
    source_kinds: ["official"] },
];

/* ─────────────────────────────────────────────────────────────────
 * 港口錨地 / Anchorage Areas — 獨立於 RISK_ZONES，對應 anchorage 維度監控
 * 涵蓋亞洲 East Asia / Southeast Asia / South Asia 主要商港 41 個
 * Demo 資料：邊界為近似值（港口中心 ±0.08° 5 點多邊形）
 * ───────────────────────────────────────────────────────────────── */
window.ANCHORAGE_AREAS = [
  { id: "ANC-CNSHA", port_code: "CNSHA",
    port_name: "Shanghai Outer Anchorages", port_name_cn: "上海港外錨地",
    region: "East Asia / China",
    desc: "長江口外與洋山深水港外錨地近似範圍",
    source: "Shanghai MSA chart 參考近似",
    coords: [[31.50,121.70],[31.50,122.40],[30.95,122.40],[30.55,122.25],[30.55,122.05],[31.15,121.70]],
    source_kinds: ["official"] },
  { id: "ANC-CNNGB", port_code: "CNNGB",
    port_name: "Ningbo-Zhoushan Outer Anchorages", port_name_cn: "寧波舟山港外錨地",
    region: "East Asia / China",
    desc: "寧波舟山港外與螺頭水道附近錨地近似範圍",
    source: "Ningbo MSA chart 參考近似",
    coords: [[30.10,121.85],[30.10,122.30],[29.75,122.30],[29.75,121.85]],
    source_kinds: ["web"] },
  { id: "ANC-CNQIN", port_code: "CNQIN",
    port_name: "Qingdao", port_name_cn: "青島",
    region: "East Asia / China",
    coords: [[36.15,120.32000000000001],[36.15,120.48],[36.07,120.49600000000001],[35.99,120.48],[35.99,120.32000000000001]],
    source_kinds: ["official"] },
  { id: "ANC-CNTAO", port_code: "CNTAO",
    port_name: "Tianjin / Xingang", port_name_cn: "天津新港",
    region: "East Asia / China",
    coords: [[39.07,117.7],[39.07,117.86],[38.99,117.876],[38.910000000000004,117.86],[38.910000000000004,117.7]],
    source_kinds: ["doc", "official"] },
  { id: "ANC-CNDLC", port_code: "CNDLC",
    port_name: "Dalian", port_name_cn: "大連",
    region: "East Asia / China",
    coords: [[39,121.58],[39,121.74],[38.92,121.756],[38.84,121.74],[38.84,121.58]],
    source_kinds: ["doc", "official"] },
  { id: "ANC-CNXMN", port_code: "CNXMN",
    port_name: "Xiamen Bay Outer Anchorages", port_name_cn: "環廈門灣港外推薦錨區（閩廈港外 11-17）",
    region: "East Asia / China",
    desc: "中國海事局公布閩廈港外 11/12/14/15/16/17 共 6 個推薦錨區，涵蓋環廈門灣（廈門 / 漳州 / 泉州外港）水域",
    source: "中華人民共和國海事局《關於公佈環廈門灣水域港外推薦錨區的通告》",
    coords: [[24.55,117.85],[24.55,118.25],[24.30,118.40],[24.05,118.30],[24.05,117.85]],
    source_kinds: ["doc", "official"] },
  { id: "ANC-CNZHA", port_code: "CNZHA",
    port_name: "Zhangzhou Outer Anchorages", port_name_cn: "漳州港外錨地",
    region: "East Asia / China",
    desc: "漳州外港錨地（涵蓋於環廈門灣港外推薦錨區範圍內，含古雷 / 招商局碼頭外港等）",
    source: "中華人民共和國海事局 / 漳州海事局 參考近似",
    coords: [[24.10,117.70],[24.10,117.95],[23.85,117.95],[23.85,117.70]],
    source_kinds: ["doc", "official"] },
  { id: "ANC-CNQUZ", port_code: "CNQUZ",
    port_name: "Quanzhou Outer Anchorages", port_name_cn: "泉州港外錨地",
    region: "East Asia / China",
    desc: "泉州港外錨地（含圍頭灣 / 肖厝 / 斗尾 等深水錨地）",
    source: "福建海事局 參考近似",
    coords: [[24.95,118.85],[24.95,119.10],[24.70,119.10],[24.70,118.85]],
    source_kinds: ["doc", "official"] },
  { id: "ANC-CNPTN", port_code: "CNPTN",
    port_name: "Pingtan Outer Anchorages", port_name_cn: "平潭港外錨地",
    region: "East Asia / China",
    desc: "平潭港外錨地（草嶼錨地 / 石牌錨地 / 白薑錨地 / 引航檢疫錨地）",
    source: "福州港港口章程 / 福建海事局",
    coords: [[25.45,119.78],[25.45,119.95],[25.30,119.95],[25.30,119.78]] },
  { id: "ANC-CNPTI", port_code: "CNPTI",
    port_name: "Putian Outer Anchorages", port_name_cn: "莆田港外錨地",
    region: "East Asia / China",
    desc: "莆田港外錨地（含秀嶼港 / 東吳港 / 興化灣 等錨地）",
    source: "福建海事局 參考近似",
    coords: [[25.45,119.10],[25.45,119.35],[25.20,119.35],[25.20,119.10]] },
  { id: "ANC-CNNDE", port_code: "CNNDE",
    port_name: "Ningde / Sandu Ao Outer Anchorages", port_name_cn: "寧德三都澳港外錨地",
    region: "East Asia / China",
    desc: "三都澳東衝口錨地 + 30 萬噸級散貨船候潮錨地 + 官井洋錨地（10 萬噸級船舶待泊）",
    source: "福州港港口章程 / 寧德海事局",
    coords: [[26.65,119.78],[26.65,120.00],[26.45,120.00],[26.45,119.78]] },
  { id: "ANC-CNYTN", port_code: "CNYTN",
    port_name: "Yantian / Shenzhen Outer Anchorages", port_name_cn: "深圳鹽田港外錨地",
    region: "East Asia / China",
    desc: "大鵬灣外鹽田港錨地近似範圍",
    source: "Shenzhen MSA chart 參考近似",
    coords: [[22.62,114.20],[22.62,114.40],[22.50,114.40],[22.50,114.20]] },
  { id: "ANC-CNSHK", port_code: "CNSHK",
    port_name: "Shekou (Shenzhen)", port_name_cn: "蛇口",
    region: "East Asia / China",
    coords: [[22.56,113.84],[22.56,114],[22.48,114.016],[22.400000000000002,114],[22.400000000000002,113.84]] },
  { id: "ANC-CNFOC", port_code: "CNFOC",
    port_name: "Fuzhou Jiangyin Anchorage 15W-DWT", port_name_cn: "福州江陰小月嶼 15 萬噸級錨地",
    region: "East Asia / China",
    desc: "福州江陰港主要候潮錨地，5 萬噸級船舶候潮 / 引水 / 檢疫，水深 19-24.1 m（4 點 M1-M4）",
    source: "福州港港口章程 2022.08",
    coords: [[25.221944,119.682778],[25.212778,119.705000],[25.231944,119.695278],[25.241111,119.673611]] },
  { id: "ANC-HKHKG", port_code: "HKHKG",
    port_name: "Hong Kong Anchorages", port_name_cn: "香港錨地",
    region: "East Asia / Hong Kong",
    desc: "涵蓋 Western / Eastern / Tathong / 南丫西 等錨區 — 近似範圍",
    source: "HK Marine Department chart 參考近似",
    coords: [[22.32,114.08],[22.32,114.25],[22.22,114.28],[22.16,114.16],[22.18,114.08]] },
  { id: "ANC-TWKHH-1", port_code: "TWKHH",
    port_name: "Kaohsiung Anchorage 1", port_name_cn: "高雄第一錨區",
    region: "East Asia / Taiwan",
    desc: "進入一港口之中小型船舶及危險品船舶備用錨區（約 11 個錨位）",
    source: "高雄港務分公司 https://kh.twport.com.tw/service/Articles?a=1051",
    coords: [[22.643333,120.249722],[22.665,120.211667],[22.644444,120.211111],[22.620833,120.256944]] },
  { id: "ANC-TWKHH-2", port_code: "TWKHH",
    port_name: "Kaohsiung Anchorage 2", port_name_cn: "高雄第二錨區",
    region: "East Asia / Taiwan",
    desc: "進出一港口船舶（不含危險品船）錨泊（約 18 個錨位）",
    source: "高雄港務分公司 https://kh.twport.com.tw/service/Articles?a=1051",
    coords: [[22.617778,120.251944],[22.616667,120.202778],[22.591667,120.211389],[22.591667,120.270278]] },
  { id: "ANC-TWKHH-3", port_code: "TWKHH",
    port_name: "Kaohsiung Anchorage 3", port_name_cn: "高雄第三錨區",
    region: "East Asia / Taiwan",
    desc: "進出二港口中小型船舶（不含危險品船）錨泊（約 10 個錨位）",
    source: "臺灣港務《各國際商港錨泊使用管理規定》108 年 8 月",
    coords: [[22.571667,120.263056],[22.578611,120.279167],[22.567222,120.263333],[22.570278,120.261111],[22.551111,120.296111],[22.550000,120.225000],[22.571667,120.218333]] },
  { id: "ANC-TWKHH-4", port_code: "TWKHH",
    port_name: "Kaohsiung Anchorage 4", port_name_cn: "高雄第四錨區",
    region: "East Asia / Taiwan",
    desc: "大型散裝及貨櫃船、危險品備用（約 10 個錨位）— PDF 未列 D2，4 點近似",
    source: "臺灣港務《各國際商港錨泊使用管理規定》108 年 8 月",
    coords: [[22.547500,120.298889],[22.529444,120.309722],[22.508333,120.249722],[22.526111,120.238611]] },
  { id: "ANC-TWKHH-5", port_code: "TWKHH",
    port_name: "Kaohsiung Dangerous Goods Anchorage", port_name_cn: "高雄危險品船專用錨區",
    region: "East Asia / Taiwan",
    desc: "專供危險品船拋錨使用，其他船舶不得進入（約 12 個錨位）",
    source: "臺灣港務《各國際商港錨泊使用管理規定》108 年 8 月",
    coords: [[22.591667,120.211389],[22.591667,120.270278],[22.581667,120.277222],[22.571667,120.263056],[22.571667,120.218333]] },
  { id: "ANC-TWKEL", port_code: "TWKEL",
    port_name: "Keelung Anchorage", port_name_cn: "基隆港外海錨泊區",
    region: "East Asia / Taiwan",
    desc: "基隆港外海錨泊區，北防波堤北 1–1.5 浬，水深 32–70 m 沙泥底（WGS-84），4 點 A1-A4",
    source: "臺灣港務《各國際商港錨泊使用管理規定》108 年 8 月",
    coords: [[25.170278,121.736667],[25.210556,121.729444],[25.215833,121.706389],[25.185833,121.697222]] },
  { id: "ANC-TWTXG", port_code: "TWTXG",
    port_name: "Taichung Anchorage", port_name_cn: "臺中港外海錨泊區",
    region: "East Asia / Taiwan",
    desc: "臺中港外海錨泊區 6 點 A-F；A-B-C-D 連線以北 + 經度 120°25′ E 以東為禁止錨泊區",
    source: "臺灣港務《各國際商港錨泊使用管理規定》108 年 8 月",
    coords: [[24.281028,120.494556],[24.281028,120.483167],[24.263528,120.450389],[24.263528,120.436778],[24.233250,120.429833],[24.233250,120.466500]] },
  { id: "ANC-TWTPP", port_code: "TWTPP",
    port_name: "Taipei Anchorage", port_name_cn: "臺北港外海錨泊區",
    region: "East Asia / Taiwan",
    desc: "臺北港外海錨泊區 4 點 A/B/C/D（WGS-84）",
    source: "臺灣港務《各國際商港錨泊使用管理規定》108 年 8 月",
    coords: [[25.170500,121.343167],[25.182833,121.368000],[25.177333,121.373333],[25.164500,121.347833]] },
  { id: "ANC-KRPUS", port_code: "KRPUS",
    port_name: "Busan Anchorages", port_name_cn: "釜山港錨地",
    region: "East Asia / Korea",
    desc: "Busan 北港 + 新港外錨地近似範圍",
    source: "Busan Port Authority chart 參考近似",
    coords: [[35.14,129.00],[35.14,129.18],[35.04,129.20],[34.95,129.10],[34.98,128.95]] },
  { id: "ANC-KRINC", port_code: "KRINC",
    port_name: "Incheon", port_name_cn: "仁川",
    region: "East Asia / Korea",
    coords: [[37.54,126.54],[37.54,126.7],[37.46,126.71600000000001],[37.38,126.7],[37.38,126.54]] },
  { id: "ANC-KRKAN", port_code: "KRKAN",
    port_name: "Gwangyang", port_name_cn: "光陽",
    region: "East Asia / Korea",
    coords: [[35,127.66],[35,127.82],[34.92,127.836],[34.84,127.82],[34.84,127.66]] },
  { id: "ANC-KRULS", port_code: "KRULS",
    port_name: "Ulsan", port_name_cn: "蔚山",
    region: "East Asia / Korea",
    coords: [[35.58,129.28],[35.58,129.44000000000003],[35.5,129.45600000000002],[35.42,129.44000000000003],[35.42,129.28]] },
  { id: "ANC-JPTYO", port_code: "JPTYO",
    port_name: "Tokyo Bay Anchorages", port_name_cn: "東京港錨地",
    region: "East Asia / Japan",
    desc: "東京港外錨地（含 Daini / Honma 等）— 近似範圍",
    source: "Tokyo Port chart 參考近似",
    coords: [[35.66,139.78],[35.66,139.92],[35.55,139.92],[35.55,139.78]] },
  { id: "ANC-JPYOK", port_code: "JPYOK",
    port_name: "Yokohama Anchorages", port_name_cn: "橫濱港錨地",
    region: "East Asia / Japan",
    desc: "橫濱港外錨地（含 Negishi / Honmoku 等）— 近似範圍",
    source: "Yokohama Port chart 參考近似",
    coords: [[35.46,139.62],[35.46,139.74],[35.36,139.74],[35.36,139.62]] },
  { id: "ANC-JPNGO", port_code: "JPNGO",
    port_name: "Nagoya", port_name_cn: "名古屋",
    region: "East Asia / Japan",
    coords: [[35.16,136.79999999999998],[35.16,136.96],[35.08,136.976],[35,136.96],[35,136.79999999999998]] },
  { id: "ANC-JPUKB", port_code: "JPUKB",
    port_name: "Kobe", port_name_cn: "神戶",
    region: "East Asia / Japan",
    coords: [[34.76,135.11999999999998],[34.76,135.28],[34.68,135.296],[34.6,135.28],[34.6,135.11999999999998]] },
  { id: "ANC-JPOSA", port_code: "JPOSA",
    port_name: "Osaka", port_name_cn: "大阪",
    region: "East Asia / Japan",
    coords: [[34.739999999999995,135.35],[34.739999999999995,135.51000000000002],[34.66,135.526],[34.58,135.51000000000002],[34.58,135.35]] },
  { id: "ANC-JPHKT", port_code: "JPHKT",
    port_name: "Hakata (Fukuoka)", port_name_cn: "博多福岡",
    region: "East Asia / Japan",
    coords: [[33.699999999999996,130.32],[33.699999999999996,130.48000000000002],[33.62,130.496],[33.54,130.48000000000002],[33.54,130.32]] },
  { id: "ANC-SGSIN", port_code: "SGSIN",
    port_name: "Singapore Anchorages", port_name_cn: "新加坡港東/西錨區",
    region: "Southeast Asia / Singapore",
    desc: "涵蓋 Eastern (Bunkering / Petroleum / Holding A-C) + Western (VLCC / Petroleum / Sudong / Selat Pauh) — 近似範圍",
    source: "MPA chartlet 參考近似（Port of Singapore Anchorages 2021 ed.）",
    coords: [[1.32,103.55],[1.32,103.96],[1.20,103.96],[1.10,103.78],[1.10,103.55]] },
  { id: "ANC-MYPKG", port_code: "MYPKG",
    port_name: "Port Klang", port_name_cn: "巴生港",
    region: "Southeast Asia / Malaysia",
    coords: [[3.0500000000000003,101.32000000000001],[3.0500000000000003,101.48],[2.97,101.49600000000001],[2.89,101.48],[2.89,101.32000000000001]] },
  { id: "ANC-MYTPP", port_code: "MYTPP",
    port_name: "Tanjung Pelepas", port_name_cn: "丹戎柏勒巴斯",
    region: "Southeast Asia / Malaysia",
    coords: [[1.4400000000000002,103.47],[1.4400000000000002,103.63],[1.36,103.646],[1.28,103.63],[1.28,103.47]] },
  { id: "ANC-MYPEN", port_code: "MYPEN",
    port_name: "Penang", port_name_cn: "檳城",
    region: "Southeast Asia / Malaysia",
    coords: [[5.49,100.26],[5.49,100.42],[5.41,100.436],[5.33,100.42],[5.33,100.26]] },
  { id: "ANC-THLCH", port_code: "THLCH",
    port_name: "Laem Chabang", port_name_cn: "林查班",
    region: "Southeast Asia / Thailand",
    coords: [[13.14,100.8],[13.14,100.96],[13.06,100.976],[12.98,100.96],[12.98,100.8]] },
  { id: "ANC-THBKK", port_code: "THBKK",
    port_name: "Bangkok", port_name_cn: "曼谷",
    region: "Southeast Asia / Thailand",
    coords: [[13.790000000000001,100.47],[13.790000000000001,100.63],[13.71,100.646],[13.63,100.63],[13.63,100.47]] },
  { id: "ANC-VNSGN", port_code: "VNSGN",
    port_name: "Ho Chi Minh / Cai Mep", port_name_cn: "胡志明/蓋梅",
    region: "Southeast Asia / Vietnam",
    coords: [[10.63,106.96000000000001],[10.63,107.12],[10.55,107.13600000000001],[10.47,107.12],[10.47,106.96000000000001]] },
  { id: "ANC-VNHPH", port_code: "VNHPH",
    port_name: "Hai Phong", port_name_cn: "海防",
    region: "Southeast Asia / Vietnam",
    coords: [[20.939999999999998,106.61],[20.939999999999998,106.77],[20.86,106.786],[20.78,106.77],[20.78,106.61]] },
  { id: "ANC-PHMNL", port_code: "PHMNL",
    port_name: "Manila", port_name_cn: "馬尼拉",
    region: "Southeast Asia / Philippines",
    coords: [[14.67,120.88],[14.67,121.03999999999999],[14.59,121.056],[14.51,121.03999999999999],[14.51,120.88]] },
  { id: "ANC-IDJKT", port_code: "IDJKT",
    port_name: "Jakarta (Tanjung Priok)", port_name_cn: "雅加達丹戎不碌",
    region: "Southeast Asia / Indonesia",
    coords: [[-6.02,106.8],[-6.02,106.96],[-6.1,106.976],[-6.18,106.96],[-6.18,106.8]] },
  { id: "ANC-IDSUB", port_code: "IDSUB",
    port_name: "Surabaya", port_name_cn: "泗水",
    region: "Southeast Asia / Indonesia",
    coords: [[-7.12,112.65],[-7.12,112.81],[-7.2,112.82600000000001],[-7.28,112.81],[-7.28,112.65]] },
  { id: "ANC-INNSA", port_code: "INNSA",
    port_name: "Nhava Sheva (Mumbai)", port_name_cn: "尼瓦舍瓦/孟買",
    region: "South Asia / India",
    coords: [[19.029999999999998,72.87],[19.029999999999998,73.03],[18.95,73.046],[18.87,73.03],[18.87,72.87]] },
  { id: "ANC-INMAA", port_code: "INMAA",
    port_name: "Chennai", port_name_cn: "清奈",
    region: "South Asia / India",
    coords: [[13.18,80.22],[13.18,80.38],[13.1,80.396],[13.02,80.38],[13.02,80.22]] },
  { id: "ANC-INCOK", port_code: "INCOK",
    port_name: "Cochin", port_name_cn: "柯枝",
    region: "South Asia / India",
    coords: [[10.05,76.19],[10.05,76.35],[9.97,76.366],[9.89,76.35],[9.89,76.19]] },
  { id: "ANC-BDCGP", port_code: "BDCGP",
    port_name: "Chittagong Outer Anchorage", port_name_cn: "吉大港外錨地",
    region: "South Asia / Bangladesh",
    desc: "Karnaphuli 河口外、Patenga 南方孟加拉灣海面，等候靠泊",
    coords: [[22.22,91.55],[22.22,91.78],[22.13,91.80],[22.00,91.72],[22.00,91.55]] },
  { id: "ANC-LKCMB", port_code: "LKCMB",
    port_name: "Colombo", port_name_cn: "可倫坡",
    region: "South Asia / Sri Lanka",
    coords: [[7.03,79.77],[7.03,79.92999999999999],[6.95,79.946],[6.87,79.92999999999999],[6.87,79.77]] },
  { id: "ANC-PKKHI", port_code: "PKKHI",
    port_name: "Karachi", port_name_cn: "喀拉蚩",
    region: "South Asia / Pakistan",
    coords: [[24.919999999999998,66.93],[24.919999999999998,67.09],[24.84,67.10600000000001],[24.76,67.09],[24.76,66.93]] },
];
