/* ─────────────────────────────────────────────────────────────────
 * 全球海事風險區 / Global Maritime Risk Zones
 * Demo 資料：邊界為近似值，僅供介面展示。實務上請以下列權威來源即時資料為準：
 *   - IMB / ReCAAP（海盜）          - JWC / Lloyd's JWLA-027（戰爭）
 *   - OFAC / EU / UN（制裁）        - 各國 NAVAREA / NOTMAR（軍演 / 臨航）
 *   - WMO / JMA / NOAA NHC（氣象） - MARPOL Annex VI / IMO MEPC（ECA）
 *   - NOAA Fisheries / IMO MEPC（保護 / 限速）
 *   - IMO Traffic Separation Schemes（壅塞）
 *
 * 每筆 zone 欄位：
 *   cat            類別 key（對應 RISK_ZONE_CATEGORIES）
 *   id             區域代碼
 *   level          風險分級：critical / high / medium / low / info
 *   name / name_en 中／英名稱
 *   type / type_en 區域類型（次分類）
 *   desc / desc_en 中／英說明
 *   source         資料來源 / 出處
 *   source_url     來源連結（可選）
 *   effective_from 生效時間（'年-月-日' 或描述性，例如 '全年' / 'seasonal Nov–Mar'）
 *   effective_to   結束時間（'進行中' / 'ongoing' / 或日期）
 *   coords         邊界座標 [[lat, lon], ...]（leaflet polygon 用）
 * ───────────────────────────────────────────────────────────────── */

window.RISK_ZONE_CATEGORIES = [
  { key: "piracy",     label: "海盜 / 武裝搶劫高風險區", label_en: "Piracy / Armed Robbery",       color: "#ff4d4f" },
  { key: "war",        label: "戰爭 / 武裝衝突區",       label_en: "War / Armed Conflict",          color: "#a02030" },
  { key: "sanction",   label: "制裁 / 禁運 / 敏感港口", label_en: "Sanctions / Embargo",            color: "#ff8c00" },
  { key: "military",   label: "軍演 / 臨時禁航區",       label_en: "Military Exercise / NOTAM",      color: "#b069ff" },
  { key: "weather",    label: "氣象與海況高風險區",     label_en: "Weather / Heavy Seas",            color: "#1e90ff" },
  { key: "eca",        label: "環保排放管制區 (ECA)",   label_en: "Emission Control Area",           color: "#2ecc71" },
  { key: "protected",  label: "保護區 / 鯨豚限速區",     label_en: "Protected / Whale Speed Limit",  color: "#1abc9c" },
  { key: "congestion", label: "航道壅塞 / 避碰熱區",     label_en: "Congested Traffic Lane",          color: "#f5d04a" },
];

window.RISK_ZONES = [
  /* ── 1. 海盜 / 武裝搶劫高風險區 ──────────────────────────────── */
  { cat: "piracy", id: "PIR-GOG", level: "high",
    name: "幾內亞灣（西非）",  name_en: "Gulf of Guinea",
    type: "海盜熱區 / 綁架高風險", type_en: "Piracy Hotspot / Kidnap-for-Ransom",
    desc: "迦納至加彭外海，劫船與綁架事件全球居首；偽 AIS 與夜間接舷常見。建議 BMP West Africa 加固。",
    desc_en: "Côte d'Ivoire to Gabon offshore; highest crew kidnap rate worldwide. Spoofed AIS and night boarding common.",
    source: "IMB Piracy Reporting Centre / MDAT-GoG",
    source_url: "https://www.icc-ccs.org/piracy-reporting-centre",
    effective_from: "全年（長期）", effective_to: "進行中 / ongoing",
    coords: [[6.8, -5.0], [6.8, 9.0], [-2.0, 9.0], [-2.0, 2.0], [3.0, -5.0]] },

  { cat: "piracy", id: "PIR-IOR", level: "high",
    name: "亞丁灣 / 索馬利亞外海 (HRA)", name_en: "Gulf of Aden / Off Somalia (HRA)",
    type: "BMP5 高風險區 / 武裝護衛建議", type_en: "BMP5 High Risk Area / Armed escort advised",
    desc: "Bab-el-Mandeb 經亞丁灣至阿拉伯海。2022 起 IRTC 走廊縮減，但 2023 後再傳劫船事件。",
    desc_en: "Bab-el-Mandeb through Gulf of Aden into Arabian Sea. IRTC corridor narrowed in 2022; hijack attempts resumed 2023+.",
    source: "UKMTO / EU NAVFOR ATALANTA / BMP5",
    source_url: "https://www.ukmto.org",
    effective_from: "2008（長期）", effective_to: "進行中 / ongoing",
    coords: [[16, 42], [16, 60], [4, 65], [-5, 55], [0, 45], [10, 42]] },

  { cat: "piracy", id: "PIR-SS", level: "medium",
    name: "新加坡海峽 / 麻六甲", name_en: "Singapore Strait / Malacca",
    type: "錨地竊取 / 夜間登船", type_en: "Anchorage theft / Night boarding",
    desc: "錨地夜間登船竊取為主；2023 起 ReCAAP 報告再次抬升，多為機艙備品被盜。",
    desc_en: "Night-time boarding theft at anchorages; trending up per ReCAAP — typically engine-room stores theft.",
    source: "ReCAAP Information Sharing Centre",
    source_url: "https://www.recaap.org",
    effective_from: "全年", effective_to: "進行中 / ongoing",
    coords: [[3.5, 100], [3.5, 105.5], [0.5, 105.5], [-0.5, 102], [1, 99]] },

  { cat: "piracy", id: "PIR-SULU", level: "high",
    name: "蘇祿—西里伯斯海", name_en: "Sulu–Celebes Sea",
    type: "綁架勒贖區 / Abu Sayyaf", type_en: "Kidnap-for-ransom / Abu Sayyaf",
    desc: "菲律賓南部至馬來西亞東 Sabah；Abu Sayyaf 等武裝綁架。建議避開高風險走廊。",
    desc_en: "Southern Philippines to East Sabah; Abu Sayyaf-style kidnap-for-ransom. Avoid declared transit corridor.",
    source: "ReCAAP / Philippines Coast Guard advisories",
    source_url: "https://www.recaap.org",
    effective_from: "2016（長期）", effective_to: "進行中 / ongoing",
    coords: [[8, 118], [8, 124], [3, 124.5], [3, 118]] },

  { cat: "piracy", id: "PIR-CAR", level: "medium",
    name: "加勒比海 / 委內瑞拉外海", name_en: "Caribbean / Off Venezuela",
    type: "小艇武裝搶劫", type_en: "Small-craft armed robbery",
    desc: "委內瑞拉至千里達外海，小型武裝登船搶劫頻發；近岸漁船與小型遊艇為主要對象。",
    desc_en: "Venezuelan and Trinidadian waters; small-craft armed robbery — fishing vessels and yachts often targeted.",
    source: "OBP / Caribbean Safety & Security Net",
    source_url: "https://oceansbeyondpiracy.org",
    effective_from: "全年", effective_to: "進行中 / ongoing",
    coords: [[13, -73], [13, -60.5], [10, -60.5], [9, -73]] },

  /* ── 2. 戰爭 / 武裝衝突區 ─────────────────────────────────────── */
  { cat: "war", id: "WAR-BLK", level: "critical",
    name: "黑海（俄烏戰區）", name_en: "Black Sea (RU-UA war zone)",
    type: "JWLA 列管戰爭風險區", type_en: "JWLA-listed war risk area",
    desc: "JWC 列為戰爭風險區；水雷與飛彈威脅，烏俄港口進出受限；保險戰險加費 0.5–2%。",
    desc_en: "JWLA-listed; sea mines + missile threat; restricted access to UA/RU ports; war-risk premium 0.5–2%.",
    source: "JWC / Lloyd's JWLA-027",
    source_url: "https://www.lmalloyds.com",
    effective_from: "2022-02-24", effective_to: "進行中 / ongoing",
    coords: [[47.2, 28], [47.2, 41.5], [42, 41.5], [42, 28]] },

  { cat: "war", id: "WAR-RED", level: "critical",
    name: "紅海 / Bab-el-Mandeb（Houthi 攻擊）", name_en: "Red Sea / Bab-el-Mandeb (Houthi)",
    type: "飛彈 / 無人機攻擊", type_en: "Missile / UAV attacks",
    desc: "2023-11 起 Houthi 飛彈與無人機攻擊商船，多家船東已改繞好望角；Suez 通量大減 50%+。",
    desc_en: "Houthi missile/UAV attacks since Nov 2023; many operators rerouting via Cape of Good Hope; Suez transits down 50%+.",
    source: "UKMTO / CMF (Combined Maritime Forces)",
    source_url: "https://www.ukmto.org",
    effective_from: "2023-11", effective_to: "進行中 / ongoing",
    coords: [[20, 36], [20, 46], [11, 46], [11, 41]] },

  { cat: "war", id: "WAR-HORM", level: "high",
    name: "波斯灣 / 荷莫茲海峽", name_en: "Persian Gulf / Strait of Hormuz",
    type: "扣船 / GPS 干擾 / AIS 詐偽", type_en: "Vessel seizure / GPS jamming / AIS spoofing",
    desc: "伊朗革命衛隊 (IRGC) 扣船事件、GPS 干擾與假 AIS 高發；全球 30% 海運石油經此通過。",
    desc_en: "IRGC vessel seizures; GPS jamming and AIS spoofing common; 30% of seaborne oil transits here.",
    source: "UKMTO / IMSC Sentinel",
    source_url: "https://www.ukmto.org",
    effective_from: "2019-05（升級期）", effective_to: "進行中 / ongoing",
    coords: [[30, 48], [30, 58], [24, 58], [24, 48]] },

  { cat: "war", id: "WAR-EMED", level: "high",
    name: "東地中海（黎凡特）", name_en: "Eastern Mediterranean (Levant)",
    type: "區域衝突 / 海上軍事活動", type_en: "Regional conflict / Naval activity",
    desc: "以哈衝突 + 黎巴嫩外海軍事活動；保險戰險加費，部分港口列高風險區。",
    desc_en: "Israel-Hamas conflict + naval activity off Lebanon; additional war-risk premium; certain ports flagged.",
    source: "JWC / Lloyd's JWLA",
    source_url: "https://www.lmalloyds.com",
    effective_from: "2023-10", effective_to: "進行中 / ongoing",
    coords: [[35.5, 32], [35.5, 36.5], [31, 36.5], [31, 32]] },

  /* ── 3. 制裁 / 禁運 / 敏感港口區 ──────────────────────────────── */
  { cat: "sanction", id: "SAN-RU-BAL", level: "high",
    name: "俄羅斯波羅的海港口", name_en: "Russian Baltic Ports",
    type: "G7 油價上限 + EU 制裁", type_en: "G7 price cap + EU sanctions",
    desc: "Primorsk / Ust-Luga / St Petersburg — G7 油價上限 USD 60/桶；EU 第 11 套制裁限縮 P&I 與船舶服務。",
    desc_en: "Primorsk / Ust-Luga / St Petersburg — G7 USD 60/bbl price cap; EU 11th package restricts P&I and shipping services.",
    source: "OFAC / EU Council Decision 2022/1909",
    source_url: "https://ofac.treasury.gov",
    effective_from: "2022-12-05", effective_to: "進行中 / ongoing",
    coords: [[60.5, 27], [60.5, 35], [58, 35], [58, 27]] },

  { cat: "sanction", id: "SAN-IR", level: "high",
    name: "伊朗主要港口", name_en: "Iranian Ports",
    type: "OFAC 二級制裁", type_en: "OFAC secondary sanctions",
    desc: "Bandar Abbas / Kharg Island — OFAC 二級制裁風險，違反者列入 SDN 名單。",
    desc_en: "Bandar Abbas / Kharg Island — OFAC secondary sanctions exposure; violators added to SDN list.",
    source: "OFAC Iran Transactions and Sanctions Regulations",
    source_url: "https://ofac.treasury.gov",
    effective_from: "2018-11-05（重啟）", effective_to: "進行中 / ongoing",
    coords: [[28, 50], [28, 58], [25, 58], [25, 50]] },

  { cat: "sanction", id: "SAN-DPRK", level: "critical",
    name: "北韓港口", name_en: "DPRK Ports",
    type: "UN 安理會全面禁運", type_en: "UN Security Council total embargo",
    desc: "UN 安理會全面禁運；任何泊靠皆觸發 OFAC / EU / 日韓 制裁；包含 STS 與假旗識別風險。",
    desc_en: "UN Security Council total embargo; any call triggers OFAC/EU/JP/KR sanctions; STS and false-flag detection apply.",
    source: "UNSC Resolutions 1718 / 2270 / 2371 / 2397",
    source_url: "https://www.un.org/securitycouncil",
    effective_from: "2006-10-14（強化 2017）", effective_to: "進行中 / ongoing",
    coords: [[43, 124], [43, 131], [37.5, 131], [37.5, 124]] },

  { cat: "sanction", id: "SAN-VEN", level: "medium",
    name: "委內瑞拉港口", name_en: "Venezuelan Ports",
    type: "OFAC PdVSA 相關制裁", type_en: "OFAC sanctions tied to PdVSA",
    desc: "Jose / Puerto la Cruz — OFAC 對 PdVSA 與石油部相關制裁；General License 機制動態調整。",
    desc_en: "Jose / Puerto la Cruz — OFAC sanctions on PdVSA and oil ministry; subject to General License framework.",
    source: "OFAC Venezuela Sanctions Program",
    source_url: "https://ofac.treasury.gov",
    effective_from: "2019-01", effective_to: "進行中（依 GL 變化）",
    coords: [[12, -72], [12, -61], [10, -61], [10, -72]] },

  { cat: "sanction", id: "SAN-SY", level: "high",
    name: "敘利亞港口", name_en: "Syrian Ports",
    type: "EU + OFAC 禁運", type_en: "EU and OFAC embargo",
    desc: "Latakia / Tartus — EU 與 OFAC 禁運；俄海軍 Tartus 基地進出列敏感。",
    desc_en: "Latakia / Tartus — EU and OFAC embargo; calls near Russian Tartus naval base flagged.",
    source: "OFAC Syria Sanctions / EU Council Reg 36/2012",
    source_url: "https://ofac.treasury.gov",
    effective_from: "2011-05", effective_to: "進行中 / ongoing",
    coords: [[36, 35], [36, 37], [34, 37], [34, 35]] },

  { cat: "sanction", id: "SAN-CU", level: "medium",
    name: "古巴港口", name_en: "Cuban Ports",
    type: "Helms-Burton + US Embargo", type_en: "Helms-Burton + US Embargo",
    desc: "Helms-Burton Act 第 III/IV 章；多數美籍人員與美元交易受限。",
    desc_en: "Helms-Burton Act Titles III/IV; restricted for US persons and USD transactions.",
    source: "OFAC Cuban Assets Control Regulations",
    source_url: "https://ofac.treasury.gov",
    effective_from: "1962（最近強化 2017）", effective_to: "進行中 / ongoing",
    coords: [[24, -85], [24, -75], [19, -75], [19, -85]] },

  /* ── 4. 軍演 / 臨時禁航區（典型熱點，實際以最新 NOTMAR 為準） ── */
  { cat: "military", id: "MIL-TWS", level: "high",
    name: "台灣海峽", name_en: "Taiwan Strait",
    type: "PLA 演習 NOTMAR 高頻區", type_en: "Frequent PLA exercise NOTMAR",
    desc: "PLA 演習頻繁宣布臨時禁航；建議避開公告區塊；2022-08、2024-05 大規模圍島。",
    desc_en: "Frequent PLA exercise NOTMAR; avoid declared exclusion boxes; major drills 2022-08 and 2024-05.",
    source: "China MSA NAVAREA XI 公告",
    source_url: "https://www.msa.gov.cn",
    effective_from: "依公告 / per NOTMAR", effective_to: "依公告 / per NOTMAR",
    coords: [[26, 118], [26, 122], [22, 122], [22, 118]] },

  { cat: "military", id: "MIL-SCS", level: "medium",
    name: "南海", name_en: "South China Sea",
    type: "多方主權爭議 + 演習", type_en: "Multi-claimant dispute + exercises",
    desc: "西沙 / 南沙周邊多國軍演與灰色地帶活動；2016 仲裁後仍持續對峙。",
    desc_en: "Multi-claimant exercises and gray-zone activity near Paracel/Spratly; post-2016 PCA standoff continues.",
    source: "PH / VN / CN / US NAVAREA + NOTMAR",
    effective_from: "依公告 / per NOTMAR", effective_to: "依公告 / per NOTMAR",
    coords: [[20, 110], [20, 120], [7, 120], [7, 110]] },

  { cat: "military", id: "MIL-ECS", level: "medium",
    name: "東海 / 釣魚台周邊", name_en: "East China Sea / Senkaku",
    type: "爭議水域 + 海警執法", type_en: "Disputed waters + CCG/JCG presence",
    desc: "中日台爭議水域；CCG 與海保活動頻繁；2013 後 ADIZ 重疊。",
    desc_en: "Disputed waters; CCG and JCG presence; overlapping ADIZ since 2013.",
    source: "JCG NAVAREA XI / CN MSA",
    source_url: "https://www6.kaiho.mlit.go.jp",
    effective_from: "長期", effective_to: "進行中 / ongoing",
    coords: [[27, 122], [27, 127], [24, 127], [24, 122]] },

  { cat: "military", id: "MIL-KOR", level: "medium",
    name: "朝鮮半島周邊", name_en: "Korean Peninsula",
    type: "演習 + DPRK 飛彈試射", type_en: "Exercises + DPRK missile tests",
    desc: "黃海 / 東海岸演習與北韓飛彈試射禁航區；US-ROK 年度演習 4 月 & 8 月。",
    desc_en: "Yellow Sea / East Sea drills and DPRK missile-test exclusion zones; US-ROK annual exercises in Apr & Aug.",
    source: "ROK NAVAREA XIII / KCG",
    effective_from: "依公告 / per NOTMAR", effective_to: "依公告 / per NOTMAR",
    coords: [[40, 123], [40, 131], [35, 131], [35, 123]] },

  { cat: "military", id: "MIL-HAW", level: "low",
    name: "夏威夷周邊 (RIMPAC)", name_en: "Off Hawaii (RIMPAC)",
    type: "雙年度國際聯合軍演", type_en: "Biennial multinational drill",
    desc: "環太平洋軍演（雙年 6–8 月，下次 2026）；演習期間特定海域禁航。",
    desc_en: "Rim of the Pacific exercise (biennial Jun–Aug, next in 2026); designated exclusion zones during drill.",
    source: "US 3rd Fleet / USCG NAVAREA XII",
    source_url: "https://www.cpf.navy.mil",
    effective_from: "2026-06（預定）", effective_to: "2026-08（預定）",
    coords: [[24, -163], [24, -154], [18, -154], [18, -163]] },

  /* ── 5. 氣象與海況高風險區 ────────────────────────────────────── */
  { cat: "weather", id: "WX-CGH", level: "high",
    name: "好望角 / Agulhas 異常浪", name_en: "Cape of Good Hope / Agulhas Rogue Waves",
    type: "強流逆風異常浪區", type_en: "Current-against-swell rogue-wave zone",
    desc: "Agulhas 洋流逆風時生成 20 m+ 異常波；史上 World Glory (1968) 等多起斷船。",
    desc_en: "Agulhas current against SW swell — 20 m+ rogue waves; multiple historical break-ups (e.g., World Glory 1968).",
    source: "SAWS / NOAA / Smith et al. studies",
    source_url: "https://www.weathersa.co.za",
    effective_from: "5–9 月加劇", effective_to: "全年",
    coords: [[-32, 15], [-32, 24], [-38, 24], [-38, 15]] },

  { cat: "weather", id: "WX-DRAKE", level: "critical",
    name: "Drake Passage / 合恩角", name_en: "Drake Passage / Cape Horn",
    type: "強西風帶 + 冰山", type_en: "Westerlies + icebergs",
    desc: "全年強西風帶 (40°–60°S, Roaring 40s/Furious 50s)；冰山風險；建議繞道巴拿馬。",
    desc_en: "Year-round westerlies (Roaring 40s, Furious 50s); iceberg risk; Panama routing recommended where feasible.",
    source: "NOAA OPC / SHN Argentina",
    source_url: "https://ocean.weather.gov",
    effective_from: "全年", effective_to: "全年",
    coords: [[-52, -76], [-52, -54], [-62, -54], [-62, -76]] },

  { cat: "weather", id: "WX-NATL", level: "high",
    name: "北大西洋冬季風暴帶", name_en: "North Atlantic Winter Storm Belt",
    type: "冬季低壓 / 大圓修正", type_en: "Winter lows / Great-circle adjustment",
    desc: "11–3 月低壓帶 (Iceland Low)；建議大圓修正 + 氣象避陣。",
    desc_en: "Nov–Mar low-pressure track (Icelandic Low); great-circle adjustment + weather routing.",
    source: "NOAA OPC / UK Met Office",
    source_url: "https://ocean.weather.gov",
    effective_from: "11 月", effective_to: "3 月",
    coords: [[60, -50], [60, -10], [45, -10], [45, -50]] },

  { cat: "weather", id: "WX-WPAC", level: "high",
    name: "西北太平洋颱風帶", name_en: "Western North Pacific Typhoon Belt",
    type: "颱風 / 熱帶氣旋活躍區", type_en: "Active tropical cyclone basin",
    desc: "5–11 月颱風活躍；菲律賓海至日本南方平均每年 25 個命名熱帶氣旋。",
    desc_en: "Typhoon season May–Nov; Philippine Sea to southern Japan; ~25 named storms/yr on average.",
    source: "JMA RSMC Tokyo / JTWC",
    source_url: "https://www.jma.go.jp/en/typh",
    effective_from: "5 月", effective_to: "11 月",
    coords: [[28, 125], [28, 155], [10, 155], [10, 125]] },

  { cat: "weather", id: "WX-BOB", level: "medium",
    name: "孟加拉灣熱帶氣旋區", name_en: "Bay of Bengal Cyclone Area",
    type: "雙峰季節熱帶氣旋", type_en: "Bimodal cyclone season",
    desc: "4–5 月與 10–11 月雙峰季節；常侵襲印度東岸與孟加拉沿岸。",
    desc_en: "Bimodal cyclone season Apr–May and Oct–Nov; frequent landfall on east India and Bangladesh coast.",
    source: "IMD RSMC New Delhi",
    source_url: "https://mausam.imd.gov.in",
    effective_from: "4–5 月、10–11 月", effective_to: "—",
    coords: [[22, 80], [22, 95], [10, 95], [10, 80]] },

  { cat: "weather", id: "WX-BIS", level: "medium",
    name: "比斯開灣冬季湧浪", name_en: "Bay of Biscay Winter Swell",
    type: "大陸棚邊緣湧浪", type_en: "Shelf-edge breaking swell",
    desc: "大西洋低壓直擊大陸棚邊緣，冬季 6 m+ 湧浪；建議貼岸或避陣繞行。",
    desc_en: "Atlantic lows breaking over the shelf edge; 6 m+ swells in winter; coastal route or detour recommended.",
    source: "Météo-France / UK Met Office",
    source_url: "https://meteofrance.com",
    effective_from: "11 月", effective_to: "3 月",
    coords: [[48, -10], [48, -1], [43, -1], [43, -10]] },

  /* ── 6. 環保排放管制區 ECA（MARPOL Annex VI） ─────────────────── */
  { cat: "eca", id: "ECA-NA-E", level: "info",
    name: "北美 ECA（東岸）", name_en: "North American ECA (East Coast)",
    type: "SECA + NECA（硫 ≤0.1% + Tier III NOx）", type_en: "SECA + NECA (sulphur ≤0.1% + Tier III NOx)",
    desc: "200 nm 沿岸區；硫含量 ≤0.1% m/m；2016 後新造船需符合 Tier III NOx。",
    desc_en: "200-nm coastal zone; sulphur ≤0.1% m/m; Tier III NOx for newbuilds keel-laid after 2016-01-01.",
    source: "MARPOL Annex VI / IMO MEPC.176(58)",
    source_url: "https://www.imo.org",
    effective_from: "2012-08-01（硫）/ 2016-01-01（NOx）", effective_to: "進行中 / ongoing",
    coords: [[60, -52], [60, -68], [25, -82], [25, -76]] },

  { cat: "eca", id: "ECA-NA-W", level: "info",
    name: "北美 ECA（西岸）", name_en: "North American ECA (West Coast)",
    type: "SECA + NECA", type_en: "SECA + NECA",
    desc: "200 nm 沿岸區；硫含量 ≤0.1% m/m；Tier III NOx 適用新造船。",
    desc_en: "200-nm coastal zone; sulphur ≤0.1% m/m; Tier III NOx for newbuilds.",
    source: "MARPOL Annex VI / IMO MEPC.176(58)",
    source_url: "https://www.imo.org",
    effective_from: "2012-08-01 / 2016-01-01", effective_to: "進行中 / ongoing",
    coords: [[60, -135], [60, -125], [33, -116], [33, -125]] },

  { cat: "eca", id: "ECA-NS", level: "info",
    name: "北海 + 波羅的海 ECA", name_en: "North Sea + Baltic Sea ECA",
    type: "SECA + NECA", type_en: "SECA + NECA",
    desc: "硫 ≤0.1%（2015-01-01 起）；NECA Tier III NOx 2021-01-01 起新造。",
    desc_en: "Sulphur ≤0.1% (since 2015-01-01); NECA Tier III NOx for newbuilds since 2021-01-01.",
    source: "MARPOL Annex VI / IMO MEPC.286(71)",
    source_url: "https://www.imo.org",
    effective_from: "2007-11-19（硫）/ 2021-01-01（NOx）", effective_to: "進行中 / ongoing",
    coords: [[66, -2], [66, 30], [51, 30], [51, -2]] },

  { cat: "eca", id: "ECA-MED", level: "info",
    name: "地中海 SECA", name_en: "Mediterranean SECA",
    type: "SECA（硫 ≤0.1%）", type_en: "SECA (sulphur ≤0.1%)",
    desc: "整個地中海納入 SECA；硫含量 ≤0.1% m/m。",
    desc_en: "Entire Mediterranean Sea designated as SECA; sulphur ≤0.1% m/m.",
    source: "MARPOL Annex VI / IMO MEPC.361(79)",
    source_url: "https://www.imo.org",
    effective_from: "2025-05-01", effective_to: "進行中 / ongoing",
    coords: [[46, -6], [46, 36], [30, 36], [30, -6]] },

  { cat: "eca", id: "ECA-PR", level: "info",
    name: "美屬加勒比 ECA", name_en: "US Caribbean ECA",
    type: "SECA + NECA", type_en: "SECA + NECA",
    desc: "Puerto Rico / USVI 周邊 200 nm；硫 ≤0.1%。",
    desc_en: "200-nm zone around Puerto Rico / USVI; sulphur ≤0.1%.",
    source: "MARPOL Annex VI / IMO MEPC.202(62)",
    source_url: "https://www.imo.org",
    effective_from: "2014-01-01", effective_to: "進行中 / ongoing",
    coords: [[20, -68.5], [20, -64], [16, -64], [16, -68.5]] },

  /* ── 7. 保護區 / 限速區 / 鯨豚保護區 ──────────────────────────── */
  { cat: "protected", id: "PRO-NARW-NE", level: "info",
    name: "北大西洋露脊鯨 SMA（東北）", name_en: "NARW Seasonal Mgmt Area (NE US)",
    type: "強制限速區（10 kn）", type_en: "Mandatory speed limit (10 kn)",
    desc: "Cape Cod 灣季節性 SMA；≥65 ft 船舶限速 10 kn；違規最高 USD 35k 罰金。",
    desc_en: "Cape Cod Bay seasonal SMA; ≥65-ft vessels limited to 10 kn; fines up to USD 35k.",
    source: "NOAA Fisheries 50 CFR 224.105",
    source_url: "https://www.fisheries.noaa.gov",
    effective_from: "1 月 1 日", effective_to: "5 月 15 日",
    coords: [[43, -71], [43, -68], [40, -68], [40, -71]] },

  { cat: "protected", id: "PRO-NARW-SE", level: "info",
    name: "北大西洋露脊鯨 SMA（東南）", name_en: "NARW SMA (SE US)",
    type: "強制限速區（10 kn）", type_en: "Mandatory speed limit (10 kn)",
    desc: "Florida–Georgia 沿岸（NARW 育幼區）；≥65 ft 船舶限速 10 kn。",
    desc_en: "Florida–Georgia coast (NARW calving ground); ≥65-ft vessels limited to 10 kn.",
    source: "NOAA Fisheries 50 CFR 224.105",
    source_url: "https://www.fisheries.noaa.gov",
    effective_from: "11 月 15 日", effective_to: "4 月 15 日",
    coords: [[33, -82], [33, -77], [27, -77], [27, -82]] },

  { cat: "protected", id: "PRO-SBC", level: "info",
    name: "聖塔芭芭拉海峽（藍鯨）", name_en: "Santa Barbara Channel (Blue Whale)",
    type: "自願限速區 VSR（10 kn）", type_en: "Voluntary Speed Reduction (10 kn)",
    desc: "保護藍鯨 / 座頭鯨 / 長鬚鯨；自願限速 10 kn；參與率可換取碳積分。",
    desc_en: "Protects blue / humpback / fin whales; voluntary 10-kn limit; participation earns carbon credits.",
    source: "NOAA + Channel Islands National Marine Sanctuary",
    source_url: "https://channelislands.noaa.gov",
    effective_from: "5 月 1 日", effective_to: "11 月 15 日",
    coords: [[35, -121], [35, -119], [33.5, -119], [33.5, -121]] },

  { cat: "protected", id: "PRO-PEL", level: "info",
    name: "地中海 Pelagos Sanctuary", name_en: "Pelagos Sanctuary",
    type: "三國海洋哺乳動物保護區", type_en: "Trilateral marine mammal sanctuary",
    desc: "法義摩三國海洋哺乳動物保護區；避免高速、夜間航行與聲納試驗。",
    desc_en: "FR/IT/MC trilateral marine mammal sanctuary; avoid high speed, night transit and sonar trials.",
    source: "Pelagos Agreement (1999)",
    source_url: "https://www.sanctuaire-pelagos.org",
    effective_from: "2002-02-21", effective_to: "進行中 / ongoing",
    coords: [[44, 6], [44, 10], [41, 10], [41, 6]] },

  { cat: "protected", id: "PRO-GBR", level: "info",
    name: "大堡礁海洋公園", name_en: "Great Barrier Reef Marine Park",
    type: "強制引航 + IMO PSSA", type_en: "Compulsory pilotage + IMO PSSA",
    desc: "強制引航、Two-way 路徑與排放限制；IMO 特別敏感海域 (PSSA) 標誌區。",
    desc_en: "Compulsory pilotage, two-way routes and discharge limits; IMO Particularly Sensitive Sea Area (PSSA).",
    source: "AMSA / GBRMPA / IMO Resolution MEPC.133(53)",
    source_url: "https://www.amsa.gov.au",
    effective_from: "1990（PSSA 1990, 強化 2005）", effective_to: "進行中 / ongoing",
    coords: [[-10, 143], [-10, 154], [-24, 154], [-24, 145]] },

  { cat: "protected", id: "PRO-HAU", level: "info",
    name: "豪拉基灣（Bryde's 鯨）", name_en: "Hauraki Gulf (Bryde's Whale)",
    type: "自願限速 10 kn", type_en: "Voluntary 10-kn speed limit",
    desc: "保護當地稀有 Bryde's 鯨；2013 自願協議簽署後撞擊事件下降 90%。",
    desc_en: "Protects local Bryde's whale; ship strikes down 90% after the 2013 voluntary agreement.",
    source: "Auckland Council / DOC New Zealand",
    source_url: "https://www.doc.govt.nz",
    effective_from: "2013", effective_to: "進行中 / ongoing",
    coords: [[-35.5, 174.5], [-35.5, 175.5], [-37, 175.5], [-37, 174.5]] },

  /* ── 8. 航道壅塞 / 避碰高風險區 ──────────────────────────────── */
  { cat: "congestion", id: "CON-DOV", level: "high",
    name: "多佛海峽 / 英吉利海峽", name_en: "Dover Strait / English Channel",
    type: "TSS 分道通行最忙海域", type_en: "Busiest TSS in the world",
    desc: "全球最忙 TSS；雙向 ≥400 艘/日；強制 AIS + VHF Ch 11 報告（CNIS）。",
    desc_en: "Busiest TSS in the world; ≥400 transits/day bi-directional; mandatory AIS + VHF Ch 11 (CNIS).",
    source: "IMO COLREG Rule 10 / UK MCA CNIS",
    source_url: "https://www.gov.uk/government/organisations/maritime-and-coastguard-agency",
    effective_from: "1967（首條 TSS）", effective_to: "進行中 / ongoing",
    coords: [[51.5, 0.8], [51.5, 2.5], [50.5, 2.5], [50.5, 0.8]] },

  { cat: "congestion", id: "CON-SS", level: "high",
    name: "新加坡海峽 TSS", name_en: "Singapore Strait TSS",
    type: "東西向主幹 + 高會遇率", type_en: "Main E-W lane + high encounter rate",
    desc: "東西向幹線；錨地飽和、會遇率高；2024 起 STRAITREP 強制報告升級。",
    desc_en: "Main E-W lane; saturated anchorages, high encounter rate; STRAITREP mandatory reporting since 2024.",
    source: "IMO STRAITREP / MPA Singapore",
    source_url: "https://www.mpa.gov.sg",
    effective_from: "1981（強化 1998）", effective_to: "進行中 / ongoing",
    coords: [[3, 100], [3, 105.5], [0.7, 105.5], [0.7, 100]] },

  { cat: "congestion", id: "CON-SUE", level: "high",
    name: "蘇伊士運河進出區", name_en: "Suez Canal Approaches",
    type: "運河排隊 + 錨地擁擠", type_en: "Canal queuing + anchorage congestion",
    desc: "排隊等候 + 蘇伊士灣錨地擁擠；2021 Ever Given 後限速與護航管制趨嚴。",
    desc_en: "Queueing + Suez Bay anchorage congestion; stricter speed and escort rules post-Ever Given (2021).",
    source: "Suez Canal Authority (SCA)",
    source_url: "https://www.suezcanal.gov.eg",
    effective_from: "全年（峰季 11–3 月）", effective_to: "—",
    coords: [[32, 32], [32, 33.5], [29, 33.5], [29, 32]] },

  { cat: "congestion", id: "CON-BOS", level: "medium",
    name: "博斯普魯斯海峽", name_en: "Bosphorus Strait",
    type: "土耳其單向通行 + 強流", type_en: "Turkey one-way traffic + strong currents",
    desc: "土耳其單向通行；霧季與夜間特別管制；6–8 節向南表層流。",
    desc_en: "Turkey one-way traffic; fog/night restrictions; 6–8 kn southbound surface current.",
    source: "Turkish Straits VTS",
    source_url: "https://atlas.kiyiemniyeti.gov.tr",
    effective_from: "1994（VTS 1998）", effective_to: "進行中 / ongoing",
    coords: [[41.4, 28.5], [41.4, 29.5], [40.9, 29.5], [40.9, 28.5]] },

  { cat: "congestion", id: "CON-GIB", level: "medium",
    name: "直布羅陀海峽", name_en: "Strait of Gibraltar",
    type: "大西洋—地中海主幹", type_en: "Atlantic–Mediterranean artery",
    desc: "東西大西洋—地中海主幹；強逆流、橫向渡輪交織。",
    desc_en: "Main Atlantic-Med artery; strong reverse currents, crossing ferries.",
    source: "Tarifa Traffic / SASEMAR",
    source_url: "https://www.salvamentomaritimo.es",
    effective_from: "1996（TSS）", effective_to: "進行中 / ongoing",
    coords: [[36.5, -6.5], [36.5, -5], [35.5, -5], [35.5, -6.5]] },

  { cat: "congestion", id: "CON-HOU", level: "medium",
    name: "休士頓船道", name_en: "Houston Ship Channel",
    type: "窄航道 + 高小艇密度", type_en: "Narrow channel + heavy small craft",
    desc: "美國第一大石化貨港；窄航道（530 ft 寬）與大量小艇；2031 拓寬至 700 ft。",
    desc_en: "Largest US petrochem port; narrow channel (530 ft) with heavy small-craft traffic; widening to 700 ft by 2031.",
    source: "USCG Sector Houston-Galveston",
    source_url: "https://www.uscg.mil",
    effective_from: "全年", effective_to: "進行中 / ongoing",
    coords: [[30, -95], [30, -94.5], [29, -94.5], [29, -95]] },

  { cat: "congestion", id: "CON-PAN", level: "medium",
    name: "巴拿馬運河進出區", name_en: "Panama Canal Approaches",
    type: "運河枯水減班 + 標位拍賣", type_en: "Drought-driven transit cuts + slot auction",
    desc: "Gatún Lake 枯水減班；2023 起每日通量從 36 降至 22；標位拍賣常態化。",
    desc_en: "Drought-cut transits from 36 to 22/day since 2023; auction-based slots common.",
    source: "Panama Canal Authority (ACP)",
    source_url: "https://www.pancanal.com",
    effective_from: "2023-08（限額）", effective_to: "進行中 / ongoing",
    coords: [[10, -80.5], [10, -78.5], [8.2, -78.5], [8.2, -80.5]] },
];
